"""The ``whygraph install`` subcommand — emit the host shim installer.

WhyGraph ships as a single Docker image. This command prints a POSIX ``sh``
installer to **stdout** so the whole install is one Docker-native line::

    docker run --rm ghcr.io/mtrdesign/whygraph install | sh

The image auto-pulls on first use, this command emits the installer, and the
host ``sh`` writes two shims — ``whygraph`` and ``whygraph-mcp`` — onto
``PATH``. Each shim runs the image ephemerally against the current directory
(``docker run --rm -v "$PWD:/workspace" …``), so every command is a fresh
process reading that repo's own ``whygraph.toml`` / ``.whygraph`` / ``.codegraph``.

The image reference baked into the shims is ``ghcr.io/mtrdesign/whygraph`` at
the version baked into the image at build time (``WHYGRAPH_VERSION`` env, set by
the publish workflow), so an install freezes to a **concrete release** even when
pulled via ``:latest``. Each shim still honours a ``WHYGRAPH_IMAGE`` override at
run time for mirrors / local builds.

Notes
-----
Only the installer script is written to stdout (via :func:`click.echo`); all
logging goes to stderr. That keeps the ``… | sh`` pipe clean — the container's
stderr surfaces on the terminal but never corrupts the piped script.
"""

from __future__ import annotations

import os

import click

IMAGE_REPO = "ghcr.io/mtrdesign/whygraph"
"""Canonical published image; the baked default for the generated shims."""

_SHIM_TEMPLATE = """\
#!/usr/bin/env sh
# WhyGraph shim — runs '__NAME__' inside the WhyGraph container against the
# current directory. Generated by `whygraph install`; safe to re-generate.
set -eu
IMAGE="${WHYGRAPH_IMAGE:-__IMAGE__}"

# Allocate a TTY only when attached to one, so progress bars render
# interactively but pipes / CI / MCP-over-stdio still work.
tty=""
[ -t 0 ] && [ -t 1 ] && tty="-t"

# --user + HOME=/tmp so files written into the repo (.whygraph/, .codegraph/)
# are owned by the host user and git sees matching ownership (no "dubious
# ownership"). Tokens / LLM keys pass through from the host env when set.
exec docker run --rm -i $tty \\
    --user "$(id -u):$(id -g)" -e HOME=/tmp \\
    -v "$PWD:/workspace" -w /workspace \\
    -e GH_TOKEN -e GITHUB_TOKEN \\
    -e ANTHROPIC_API_KEY -e OPENAI_API_KEY -e DEEPSEEK_API_KEY \\
    "$IMAGE" __NAME__ "$@"
"""

# The `whygraph` shim carries a `serve` branch on top of the ephemeral path:
# every command runs ephemerally EXCEPT `whygraph serve`, which publishes a
# loopback port and manages a named, long-lived container. The shim (host shell)
# owns docker + lifecycle; the Python CLI inside the container owns only uvicorn.
# Port is fully shim-controlled via WHYGRAPH_PORT so `-p` and the in-container
# `--port` can never disagree — hence no `"$@"` passthrough on the serve path.
_WHYGRAPH_SHIM_TEMPLATE = """\
#!/usr/bin/env sh
# WhyGraph shim. Every command runs ephemerally in the container EXCEPT
# `whygraph serve`, which publishes a port and manages the server container.
# Generated by `whygraph install`; safe to re-generate.
set -eu
IMAGE="${WHYGRAPH_IMAGE:-__IMAGE__}"

if [ "${1:-}" = "serve" ]; then
    NAME="whygraph-serve"
    PORT="${WHYGRAPH_PORT:-8765}"
    case "${2:-}" in
        --stop) exec docker rm -f "$NAME" ;;
        --logs) exec docker logs -f "$NAME" ;;
        --help) exec docker run --rm "$IMAGE" whygraph serve --help ;;
        --detach|-d) run="docker run -d" ;;
        "")          run="docker run --rm -i" ;;
        *) echo "whygraph serve: unknown arg '$2' (port is set via WHYGRAPH_PORT)" >&2; exit 2 ;;
    esac
    # Clear any stale same-named container so a fresh start never collides.
    docker rm -f "$NAME" >/dev/null 2>&1 || true
    # `-p 127.0.0.1:` keeps it loopback-only; `--host 0.0.0.0` lets the forward
    # reach uvicorn inside the container. Same --user/HOME + token passthrough
    # as every other command.
    exec $run --name "$NAME" -p "127.0.0.1:$PORT:$PORT" \\
        --user "$(id -u):$(id -g)" -e HOME=/tmp \\
        -v "$PWD:/workspace" -w /workspace \\
        -e GH_TOKEN -e GITHUB_TOKEN \\
        -e ANTHROPIC_API_KEY -e OPENAI_API_KEY -e DEEPSEEK_API_KEY \\
        "$IMAGE" whygraph serve --host 0.0.0.0 --port "$PORT"
fi

# Every other command — unchanged ephemeral path, no port, no name.
tty=""
[ -t 0 ] && [ -t 1 ] && tty="-t"
exec docker run --rm -i $tty \\
    --user "$(id -u):$(id -g)" -e HOME=/tmp \\
    -v "$PWD:/workspace" -w /workspace \\
    -e GH_TOKEN -e GITHUB_TOKEN \\
    -e ANTHROPIC_API_KEY -e OPENAI_API_KEY -e DEEPSEEK_API_KEY \\
    "$IMAGE" whygraph "$@"
"""

_INSTALLER_TEMPLATE = """\
#!/usr/bin/env sh
# WhyGraph installer — emitted by `whygraph install` from inside the image.
# Writes the `whygraph` and `whygraph-mcp` shims onto your PATH; each runs this
# image ephemerally against the current directory. Re-run any time to refresh.
set -eu

BIN_DIR="${WHYGRAPH_BIN_DIR:-$HOME/.local/bin}"
mkdir -p "$BIN_DIR"

cat > "$BIN_DIR/whygraph" <<'WHYGRAPH_SHIM'
__WHYGRAPH_SHIM__
WHYGRAPH_SHIM
chmod +x "$BIN_DIR/whygraph"
echo "installed $BIN_DIR/whygraph"

cat > "$BIN_DIR/whygraph-mcp" <<'WHYGRAPH_MCP_SHIM'
__WHYGRAPH_MCP_SHIM__
WHYGRAPH_MCP_SHIM
chmod +x "$BIN_DIR/whygraph-mcp"
echo "installed $BIN_DIR/whygraph-mcp"

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "note: add $BIN_DIR to your PATH, e.g. 'export PATH=\\"$BIN_DIR:\\$PATH\\"'" ;;
esac

echo "done. Try:  cd <your-repo> && whygraph init && whygraph scan"
"""


def _shim(name: str, image: str) -> str:
    """Render one shim's body for ``name``, baking ``image`` as its default.

    ``whygraph`` renders from :data:`_WHYGRAPH_SHIM_TEMPLATE` (carries the
    ``serve`` branch); ``whygraph-mcp`` renders from the simple shared
    :data:`_SHIM_TEMPLATE`.
    """
    if name == "whygraph":
        return _WHYGRAPH_SHIM_TEMPLATE.replace("__IMAGE__", image)
    return _SHIM_TEMPLATE.replace("__NAME__", name).replace("__IMAGE__", image)


def render_installer(image: str) -> str:
    """Render the full installer script that writes both shims for ``image``.

    Parameters
    ----------
    image : str
        The image reference baked as each shim's ``WHYGRAPH_IMAGE`` default,
        e.g. ``ghcr.io/mtrdesign/whygraph:1.2.3``.

    Returns
    -------
    str
        A self-contained POSIX ``sh`` script, newline-terminated.
    """
    return _INSTALLER_TEMPLATE.replace(
        "__WHYGRAPH_MCP_SHIM__", _shim("whygraph-mcp", image).rstrip("\n")
    ).replace("__WHYGRAPH_SHIM__", _shim("whygraph", image).rstrip("\n"))


@click.command(name="install")
def install_cmd() -> None:
    """Emit the host shim installer (`docker run … install | sh`).

    Prints a POSIX ``sh`` script that installs the ``whygraph`` and
    ``whygraph-mcp`` shims onto ``PATH``. The shims are pinned to
    ``ghcr.io/mtrdesign/whygraph`` at this image's baked ``WHYGRAPH_VERSION``
    (``latest`` for un-versioned local builds), overridable per command via the
    ``WHYGRAPH_IMAGE`` environment variable.
    """
    version = os.environ.get("WHYGRAPH_VERSION", "latest")
    image = f"{IMAGE_REPO}:{version}"
    click.echo(render_installer(image), nl=False)


__all__ = ["install_cmd", "render_installer", "IMAGE_REPO"]
