"""The ``whygraph install`` subcommand — emit the host shim installer.

WhyGraph ships as a single Docker image. This command prints a POSIX ``sh``
installer to **stdout**; running it writes two shims — ``whygraph`` and
``whygraph-mcp`` — onto ``PATH``. Each shim runs the image ephemerally against
the current directory (``docker run --rm -v "$PWD:/workspace" …``), so every
command is a fresh process reading that repo's own ``whygraph.toml`` /
``.whygraph`` / ``.codegraph``.

This is **in-image plumbing, not the user-facing install step**. The front door
is the host-side bootstrapper ``scripts/install.sh``, fetched from a tag-pinned
raw URL::

    curl -fsSL https://raw.githubusercontent.com/mtrdesign/whygraph/v1.1.2/scripts/install.sh | sh

That script probes Docker, pulls the pinned image, and then delegates here —
``docker run --rm IMAGE whygraph install`` — checking the output is non-empty
before executing it. Keeping generation in Python (rather than in the fetched
shell) means the shim bodies stay covered by ``tests/test_install_cmd.py`` and
cannot drift from the bootstrapper. Running that delegation by hand
(``docker run --rm IMAGE whygraph install | sh``) remains supported for
no-curl / air-gapped hosts, and printing it without the pipe is the way to
inspect exactly what would be written.

The image reference baked into the shims is ``ghcr.io/mtrdesign/whygraph`` at
the version baked into the image at build time (``WHYGRAPH_VERSION`` env, set by
the publish workflow), so an install freezes to a **concrete release** even when
pulled via ``:latest``. Each shim still honours a ``WHYGRAPH_IMAGE`` override at
run time for mirrors / local builds.

Notes
-----
Only the installer script is written to stdout (via :func:`click.echo`); all
logging goes to stderr. That keeps the ``… | sh`` pipe clean — the container's
stderr surfaces on the terminal but never corrupts the piped script.
"""

from __future__ import annotations

import os

import click

IMAGE_REPO = "ghcr.io/mtrdesign/whygraph"
"""Canonical published image; the baked default for the generated shims."""

_SHIM_TEMPLATE = """\
#!/usr/bin/env sh
# WhyGraph shim — runs '__NAME__' inside the WhyGraph container against the
# current directory. Generated by `whygraph install`; safe to re-generate.
set -eu
IMAGE="${WHYGRAPH_IMAGE:-__IMAGE__}"

# Allocate a TTY only when attached to one, so progress bars render
# interactively but pipes / CI / MCP-over-stdio still work.
tty=""
[ -t 0 ] && [ -t 1 ] && tty="-t"

# --user + HOME=/tmp so files written into the repo (.whygraph/, .codegraph/)
# are owned by the host user and git sees matching ownership (no "dubious
# ownership"). Tokens / LLM keys pass through from the host env when set.
exec docker run --rm -i $tty \\
    --user "$(id -u):$(id -g)" -e HOME=/tmp \\
    -v "$PWD:/workspace" -w /workspace \\
    -e GH_TOKEN -e GITHUB_TOKEN \\
    -e ANTHROPIC_API_KEY -e OPENAI_API_KEY -e DEEPSEEK_API_KEY \\
    -e OPENROUTER_API_KEY \\
    "$IMAGE" __NAME__ "$@"
"""

_PORTAL_VERBS = r"""
# --- portal verbs: up / down / status / logs / folders ---------------------
# `whygraph up` runs the portal in ONE named, long-lived container. Nothing from
# the host environment reaches it (keys live in the portal DB), so no `-e` here
# passes a credential variable. Config lives under ~/.config/whygraph, the
# portal's data under ~/.local/share/whygraph (mounted at /data).
portal_die() { echo "whygraph: $*" >&2; exit 2; }

portal_state() {
    docker inspect --type container -f '{{.State.Status}}' "$PORTAL" 2>/dev/null || true
}

portal_label() {
    docker inspect --type container -f '{{index .Config.Labels "'"$1"'"}}' "$PORTAL" 2>/dev/null || true
}

portal_valid_port() {
    case "$1" in ''|*[!0-9]*) portal_die "invalid port '$1'" ;; esac
    if [ "$1" -lt 1 ] || [ "$1" -gt 65535 ]; then portal_die "invalid port '$1'"; fi
}

# Precedence: the persisted port (`up --port N` writes it), then the exported
# WHYGRAPH_PORT, then 8765.
portal_resolve_port() {
    PORT=""
    if [ -f "$CONF/port" ]; then read -r PORT < "$CONF/port" || true; fi
    [ -n "$PORT" ] || PORT="${WHYGRAPH_PORT:-8765}"
    portal_valid_port "$PORT"
}

# The data dir must exist, owned by the host user, before `docker run`: a
# missing bind source is otherwise created root-owned on a Linux engine.
portal_prepare() {
    mkdir -p "$DATA" "$HOME/.config/whygraph" && chmod 700 "$DATA"
    DATA=$(cd -- "$DATA" && pwd -P)
    case "$DATA" in *,*|*\"*) portal_die "data directory '$DATA' must not contain ',' or a double quote" ;; esac
    touch "$FOLDERS_FILE"
}

# True when $1 is the data dir, inside it, or contains it.
portal_overlaps_data() {
    case "$1/" in "$DATA"/*) return 0 ;; esac
    case "$DATA/" in "$1"/*) return 0 ;; esac
    return 1
}

# Validate and canonicalise a shared folder into $NORM (exits 2 on refusal).
# ':' would break WHYGRAPH_SHARED_FOLDERS, ',' and '"' would break --mount.
portal_norm_folder() {
    case "$1" in
        *:*|*,*|*\"*|*"$NL"*)
            portal_die "shared folder '$1': ':' ',' double quotes and newlines are not allowed in the path" ;;
    esac
    [ -d "$1" ] || portal_die "shared folder '$1' is not a directory"
    NORM=$(cd -- "$1" && pwd -P) || portal_die "cannot resolve shared folder '$1'"
    case "$NORM" in
        *:*|*,*|*\"*|*"$NL"*)
            portal_die "shared folder '$NORM': ':' ',' double quotes and newlines are not allowed in the path" ;;
    esac
    [ "$NORM" != "/" ] || portal_die "refusing to share '/'"
    if portal_overlaps_data "$NORM"; then
        portal_die "shared folder '$NORM' overlaps the data directory '$DATA'"
    fi
}

# Validate one --add-folder argument and queue it (deduped) for the folders file.
portal_queue_folder() {
    portal_norm_folder "$1"
    if [ "$NORM" = "$(cd -- "$HOME" && pwd -P)" ]; then
        echo "warning: sharing your home directory exposes every project under it; prefer a narrower folder" >&2
    fi
    if grep -Fxq -e "$NORM" "$FOLDERS_FILE"; then return 0; fi
    case "$NL$pending$NL" in *"$NL$NORM$NL"*) return 0 ;; esac
    pending="${pending:+$pending$NL}$NORM"
}

# Once only (sentinel): names of credential variables set on the host, never values.
portal_env_hint() {
    [ ! -e "$CONF/env-hint-shown" ] || return 0
    names=""
    for v in GH_TOKEN GITHUB_TOKEN ANTHROPIC_API_KEY OPENAI_API_KEY DEEPSEEK_API_KEY OPENROUTER_API_KEY; do
        eval "val=\${$v:-}"
        if [ -n "$val" ]; then names="${names:+$names, }$v"; fi
    done
    [ -n "$names" ] || return 0
    echo "note: $names are set in your shell but do not reach the portal. Enter keys and tokens under Settings in the portal." >&2
    : > "$CONF/env-hint-shown"
}

portal_up() {
    new_port=""
    port_given=""
    pending=""
    while [ $# -gt 0 ]; do
        case "$1" in
            --port) [ $# -ge 2 ] || portal_die "--port needs a value"; new_port="$2"; port_given=1; shift 2 ;;
            --port=*) new_port="${1#--port=}"; port_given=1; shift ;;
            --add-folder) [ $# -ge 2 ] || portal_die "--add-folder needs a directory"; portal_queue_folder "$2"; shift 2 ;;
            --add-folder=*) portal_queue_folder "${1#--add-folder=}"; shift ;;
            -h|--help) echo "usage: whygraph up [--port N] [--add-folder DIR]..."; exit 0 ;;
            *) portal_die "whygraph up: unknown arg '$1'" ;;
        esac
    done
    [ -z "$port_given" ] || portal_valid_port "$new_port"
    [ -z "$pending" ] || printf '%s\n' "$pending" >> "$FOLDERS_FILE"
    [ -z "$port_given" ] || printf '%s\n' "$new_port" > "$CONF/port"
    portal_resolve_port

    # Same-path bind mounts, built with `set --` so paths with spaces survive.
    # `--mount` (unlike `-v`) errors on a missing source instead of creating it.
    set -- --mount "type=bind,source=$DATA,target=/data"
    FOLDERS_JOINED=""
    while IFS= read -r f || [ -n "$f" ]; do
        [ -n "$f" ] || continue
        [ -d "$f" ] || portal_die "shared folder '$f' no longer exists (remove it: whygraph folders --remove '$f')"
        if portal_overlaps_data "$f"; then portal_die "shared folder '$f' overlaps the data directory '$DATA'"; fi
        set -- "$@" --mount "type=bind,source=$f,target=$f"
        FOLDERS_JOINED="${FOLDERS_JOINED:+$FOLDERS_JOINED:}$f"
    done < "$FOLDERS_FILE"

    URL="http://127.0.0.1:$PORT"
    if docker inspect --type container -f '{{.State.Status}}' whygraph-serve >/dev/null 2>&1; then
        echo "warning: a 'whygraph-serve' container from the old playground still exists (it may hold port 8765). Remove it with: whygraph serve --stop" >&2
    fi

    state=$(portal_state)
    if [ -n "$state" ]; then
        case "$state" in
            running|restarting)
                changed=""
                [ "$(portal_label whygraph.folders)" = "$FOLDERS_JOINED" ] || changed="$changed folders"
                [ "$(portal_label whygraph.port)" = "$PORT" ] || changed="$changed port"
                [ "$(portal_label whygraph.image)" = "$IMAGE" ] || changed="$changed image"
                if [ -z "$changed" ]; then
                    if [ "$state" = "restarting" ]; then
                        echo "whygraph portal is restarting (see: whygraph logs)" >&2
                    else
                        echo "whygraph portal already running at $URL"
                    fi
                    portal_env_hint
                    return 0
                fi
                echo "whygraph portal: recreating (changed:$changed)" >&2
                docker stop -t "$GRACE" "$PORTAL" >/dev/null
                docker rm "$PORTAL" >/dev/null ;;
            *) docker rm -f "$PORTAL" >/dev/null ;;
        esac
    fi

    docker network create whygraph-portal >/dev/null 2>&1 || true
    docker run -d --init --name "$PORTAL" --restart unless-stopped \
        --network whygraph-portal --add-host=host.docker.internal:host-gateway \
        --label "whygraph.folders=$FOLDERS_JOINED" --label "whygraph.port=$PORT" \
        --label "whygraph.image=$IMAGE" \
        -p "127.0.0.1:$PORT:$PORT" \
        --user "$(id -u):$(id -g)" -e HOME=/tmp \
        "$@" \
        -e WHYGRAPH_DATA=/data -e WHYGRAPH_SHARED_FOLDERS="$FOLDERS_JOINED" \
        -e WHYGRAPH_MODE=local -e WHYGRAPH_PORT="$PORT" \
        "$IMAGE" whygraph portal --host 0.0.0.0 --port "$PORT" >/dev/null
    echo "whygraph portal running at $URL"
    portal_env_hint
}

portal_down() {
    [ $# -eq 0 ] || portal_die "whygraph down takes no arguments"
    state=$(portal_state)
    if [ -z "$state" ]; then echo "whygraph portal is not running" >&2; return 0; fi
    docker stop -t "$GRACE" "$PORTAL" >/dev/null
    docker rm "$PORTAL" >/dev/null
    echo "whygraph portal stopped"
}

portal_status() {
    [ $# -eq 0 ] || portal_die "whygraph status takes no arguments"
    state=$(portal_state)
    if [ -z "$state" ]; then echo "whygraph portal: not created (start it with: whygraph up)"; return 1; fi
    echo "whygraph portal: $state"
    echo "url: http://127.0.0.1:$(portal_label whygraph.port)"
    echo "image: $(portal_label whygraph.image)"
    folders=$(portal_label whygraph.folders)
    if [ -z "$folders" ]; then
        echo "folders: (none)"
    else
        echo "folders:"
        rest="$folders"
        while [ -n "$rest" ]; do
            case "$rest" in
                *:*) item="${rest%%:*}"; rest="${rest#*:}" ;;
                *) item="$rest"; rest="" ;;
            esac
            echo "  $item"
        done
    fi
    [ "$state" = "running" ]
}

portal_logs() {
    [ $# -eq 0 ] || portal_die "whygraph logs takes no arguments"
    exec docker logs -f "$PORTAL"
}

portal_folders() {
    remove=""
    while [ $# -gt 0 ]; do
        case "$1" in
            --remove) [ $# -ge 2 ] || portal_die "--remove needs a directory"; remove="$2"; shift 2 ;;
            --remove=*) remove="${1#--remove=}"; shift ;;
            *) portal_die "whygraph folders: unknown arg '$1'" ;;
        esac
    done
    if [ -z "$remove" ]; then
        if [ -s "$FOLDERS_FILE" ]; then cat "$FOLDERS_FILE"; else echo "no shared folders (add one: whygraph up --add-folder DIR)" >&2; fi
        return 0
    fi
    target="$remove"
    if [ -d "$remove" ]; then target=$(cd -- "$remove" && pwd -P); fi
    found=""
    : > "$FOLDERS_FILE.tmp"
    while IFS= read -r f || [ -n "$f" ]; do
        [ -n "$f" ] || continue
        if [ "$f" = "$target" ]; then found=1; else printf '%s\n' "$f" >> "$FOLDERS_FILE.tmp"; fi
    done < "$FOLDERS_FILE"
    if [ -z "$found" ]; then
        rm -f "$FOLDERS_FILE.tmp"
        echo "whygraph: '$target' is not a shared folder (see: whygraph folders)" >&2
        return 1
    fi
    mv "$FOLDERS_FILE.tmp" "$FOLDERS_FILE"
    echo "removed shared folder $target"
    # A running portal keeps its old mounts until it is recreated.
    case "$(portal_state)" in
        running|restarting) portal_prepare; portal_up ;;
    esac
}

portal_main() {
    verb="$1"; shift
    PORTAL="whygraph-portal"
    CONF="$HOME/.config/whygraph"
    FOLDERS_FILE="$CONF/folders"
    DATA="${WHYGRAPH_DATA:-$HOME/.local/share/whygraph}"
    GRACE="${WHYGRAPH_STOP_GRACE:-30}"
    NL="$(printf '\n_')"; NL="${NL%_}"
    case "$verb" in
        up) portal_prepare; portal_up "$@" ;;
        down) portal_down "$@" ;;
        status) portal_status "$@" ;;
        logs) portal_logs "$@" ;;
        folders) mkdir -p "$CONF"; touch "$FOLDERS_FILE"; portal_folders "$@" ;;
    esac
}

case "${1:-}" in
    up|down|status|logs|folders) portal_main "$@"; exit 0 ;;
esac
# --- end portal verbs ------------------------------------------------------
"""

# The `whygraph` shim carries a `serve` branch on top of the ephemeral path:
# every command runs ephemerally EXCEPT `whygraph serve`, which publishes a
# loopback port and manages a named, long-lived container. The shim (host shell)
# owns docker + lifecycle; the Python CLI inside the container owns only uvicorn.
# Port is fully shim-controlled via WHYGRAPH_PORT so `-p` and the in-container
# `--port` can never disagree — hence no `"$@"` passthrough on the serve path.
_WHYGRAPH_SHIM_TEMPLATE = """\
#!/usr/bin/env sh
# WhyGraph shim. Every command runs ephemerally in the container EXCEPT
# `whygraph up|down|status|logs|folders` (the portal container) and
# `whygraph serve`, which publish a port and manage a long-lived container.
# Generated by `whygraph install`; safe to re-generate.
set -eu
IMAGE="${WHYGRAPH_IMAGE:-__IMAGE__}"
__PORTAL_VERBS__
if [ "${1:-}" = "serve" ]; then
    NAME="whygraph-serve"
    PORT="${WHYGRAPH_PORT:-8765}"
    case "${2:-}" in
        --stop) exec docker rm -f "$NAME" ;;
        --logs) exec docker logs -f "$NAME" ;;
        --help) exec docker run --rm "$IMAGE" whygraph serve --help ;;
        --detach|-d) run="docker run -d" ;;
        "")          run="docker run --rm -i" ;;
        *) echo "whygraph serve: unknown arg '$2' (port is set via WHYGRAPH_PORT)" >&2; exit 2 ;;
    esac
    # Clear any stale same-named container so a fresh start never collides.
    docker rm -f "$NAME" >/dev/null 2>&1 || true
    # `-p 127.0.0.1:` keeps it loopback-only; `--host 0.0.0.0` lets the forward
    # reach uvicorn inside the container. Same --user/HOME + token passthrough
    # as every other command.
    exec $run --name "$NAME" -p "127.0.0.1:$PORT:$PORT" \\
        --user "$(id -u):$(id -g)" -e HOME=/tmp \\
        -v "$PWD:/workspace" -w /workspace \\
        -e GH_TOKEN -e GITHUB_TOKEN \\
        -e ANTHROPIC_API_KEY -e OPENAI_API_KEY -e DEEPSEEK_API_KEY \\
        -e OPENROUTER_API_KEY \\
        "$IMAGE" whygraph serve --host 0.0.0.0 --port "$PORT"
fi

# Every other command — unchanged ephemeral path, no port, no name.
tty=""
[ -t 0 ] && [ -t 1 ] && tty="-t"
exec docker run --rm -i $tty \\
    --user "$(id -u):$(id -g)" -e HOME=/tmp \\
    -v "$PWD:/workspace" -w /workspace \\
    -e GH_TOKEN -e GITHUB_TOKEN \\
    -e ANTHROPIC_API_KEY -e OPENAI_API_KEY -e DEEPSEEK_API_KEY \\
    -e OPENROUTER_API_KEY \\
    "$IMAGE" whygraph "$@"
"""

_INSTALLER_TEMPLATE = """\
#!/usr/bin/env sh
# WhyGraph installer — emitted by `whygraph install` from inside the image.
# Writes the `whygraph` and `whygraph-mcp` shims onto your PATH; each runs this
# image ephemerally against the current directory. Re-run any time to refresh.
set -eu

BIN_DIR="${WHYGRAPH_BIN_DIR:-$HOME/.local/bin}"
mkdir -p "$BIN_DIR"

cat > "$BIN_DIR/whygraph" <<'WHYGRAPH_SHIM'
__WHYGRAPH_SHIM__
WHYGRAPH_SHIM
chmod +x "$BIN_DIR/whygraph"
echo "installed $BIN_DIR/whygraph"

cat > "$BIN_DIR/whygraph-mcp" <<'WHYGRAPH_MCP_SHIM'
__WHYGRAPH_MCP_SHIM__
WHYGRAPH_MCP_SHIM
chmod +x "$BIN_DIR/whygraph-mcp"
echo "installed $BIN_DIR/whygraph-mcp"

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "note: add $BIN_DIR to your PATH, e.g. 'export PATH=\\"$BIN_DIR:\\$PATH\\"'" ;;
esac

echo "done. Try:  cd <your-repo> && whygraph init && whygraph scan"
"""


def _shim(name: str, image: str) -> str:
    """Render one shim's body for ``name``, baking ``image`` as its default.

    ``whygraph`` renders from :data:`_WHYGRAPH_SHIM_TEMPLATE` (carries the
    portal verbs ``up`` / ``down`` / ``status`` / ``logs`` / ``folders`` from
    :data:`_PORTAL_VERBS`, and the ``serve`` branch); ``whygraph-mcp`` renders
    from the simple shared
    :data:`_SHIM_TEMPLATE`.
    """
    if name == "whygraph":
        return _WHYGRAPH_SHIM_TEMPLATE.replace(
            "__PORTAL_VERBS__", _PORTAL_VERBS
        ).replace("__IMAGE__", image)
    return _SHIM_TEMPLATE.replace("__NAME__", name).replace("__IMAGE__", image)


def render_installer(image: str) -> str:
    """Render the full installer script that writes both shims for ``image``.

    Parameters
    ----------
    image : str
        The image reference baked as each shim's ``WHYGRAPH_IMAGE`` default,
        e.g. ``ghcr.io/mtrdesign/whygraph:1.2.3``.

    Returns
    -------
    str
        A self-contained POSIX ``sh`` script, newline-terminated.
    """
    return _INSTALLER_TEMPLATE.replace(
        "__WHYGRAPH_MCP_SHIM__", _shim("whygraph-mcp", image).rstrip("\n")
    ).replace("__WHYGRAPH_SHIM__", _shim("whygraph", image).rstrip("\n"))


@click.command(name="install")
def install_cmd() -> None:
    """Emit the host shim installer (called by ``scripts/install.sh``).

    Prints a POSIX ``sh`` script that installs the ``whygraph`` and
    ``whygraph-mcp`` shims onto ``PATH``. The shims are pinned to
    ``ghcr.io/mtrdesign/whygraph`` at this image's baked ``WHYGRAPH_VERSION``
    (``latest`` for un-versioned local builds), overridable per command via the
    ``WHYGRAPH_IMAGE`` environment variable.
    """
    version = os.environ.get("WHYGRAPH_VERSION", "latest")
    image = f"{IMAGE_REPO}:{version}"
    click.echo(render_installer(image), nl=False)


__all__ = ["install_cmd", "render_installer", "IMAGE_REPO"]
