"""initial schema

Revision ID: 1facaeb7bddb
Revises: 
Create Date: 2026-05-17 17:09:26.439020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1facaeb7bddb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('primary_login', sa.Text(), nullable=True),
    sa.Column('primary_name', sa.Text(), nullable=True),
    sa.Column('primary_email', sa.Text(), nullable=True),
    sa.Column('emails', sa.Text(), nullable=False),
    sa.Column('logins', sa.Text(), nullable=False),
    sa.Column('names', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.Text(), nullable=True),
    sa.Column('commit_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pr_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('issue_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_author_primary_email'), ['primary_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_author_primary_login'), ['primary_login'], unique=False)

    op.create_table('commit',
    sa.Column('sha', sa.Text(), nullable=True),
    sa.Column('parent_shas', sa.Text(), nullable=False),
    sa.Column('author_name', sa.Text(), nullable=False),
    sa.Column('author_email', sa.Text(), nullable=False),
    sa.Column('authored_at', sa.Text(), nullable=False),
    sa.Column('committed_at', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('insertions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.Text(), nullable=False),
    sa.Column('subject_tfidf_score', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('body_tfidf_score', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('llm_description', sa.Text(), nullable=True),
    sa.Column('llm_description_model', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sha')
    )
    with op.batch_alter_table('commit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commit_authored_at'), ['authored_at'], unique=False)

    op.create_table('issue',
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('closed_at', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('html_url', sa.Text(), nullable=False),
    sa.Column('labels', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.Text(), nullable=False),
    sa.Column('title_tfidf_score', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('body_tfidf_score', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_state'), ['state'], unique=False)

    op.create_table('pr_issue_link',
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('link_kind', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('pr_number', 'issue_number', 'link_kind')
    )
    with op.batch_alter_table('pr_issue_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_issue_link_issue_number'), ['issue_number'], unique=False)

    op.create_table('pull_request',
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('draft', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('closed_at', sa.Text(), nullable=True),
    sa.Column('merged_at', sa.Text(), nullable=True),
    sa.Column('merge_commit_sha', sa.Text(), nullable=True),
    sa.Column('head_sha', sa.Text(), nullable=False),
    sa.Column('head_ref', sa.Text(), nullable=True),
    sa.Column('base_ref', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('html_url', sa.Text(), nullable=False),
    sa.Column('labels', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.Text(), nullable=False),
    sa.Column('commit_titles', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('comments', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('title_tfidf_score', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('body_tfidf_score', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    with op.batch_alter_table('pull_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pull_request_merge_commit_sha'), ['merge_commit_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_pull_request_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pull_request_state'))
        batch_op.drop_index(batch_op.f('ix_pull_request_merge_commit_sha'))

    op.drop_table('pull_request')
    with op.batch_alter_table('pr_issue_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_issue_link_issue_number'))

    op.drop_table('pr_issue_link')
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_state'))

    op.drop_table('issue')
    with op.batch_alter_table('commit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commit_authored_at'))

    op.drop_table('commit')
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_author_primary_login'))
        batch_op.drop_index(batch_op.f('ix_author_primary_email'))

    op.drop_table('author')
    # ### end Alembic commands ###
