"""SQLModel tables of the portal database.

Every table is declared on :class:`PortalBase`, whose ``MetaData`` is its
own - **not** :data:`sqlmodel.SQLModel.metadata`. Portal tables on the
global metadata would be seen as "known" by the project ``env.py``
``include_object`` filter (``whygraph/db/migrations/env.py``) and could be
autogenerated into *project* migrations. The reverse holds too: portal
Alembic never sees a project table. A test pins both directions.

Every model sets an explicit ``__tablename__`` (a model written like the
project ones, on :class:`whygraph.db.base.WhygraphTable`, would land on
the global metadata) and every constraint is named, so a migration
can address it.

Conventions match :mod:`whygraph.db.models`: text columns are ``TEXT``,
timestamps are ISO-8601 UTC strings. ``project_config.config`` is a real
JSON column. Paths that point inside the data directory
(``projects.root`` of a GitHub clone, ``scan_runs.*_path``) are stored
**relative** to it, so a data directory can be moved.

Notes
-----
``settings.schema_version`` is called ``schema`` in the design; the
attribute would shadow pydantic's ``BaseModel.schema``.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    ForeignKeyConstraint,
    Index,
    MetaData,
    PrimaryKeyConstraint,
    Text,
    UniqueConstraint,
    event,
    inspect,
    text,
)
from sqlalchemy.orm import registry
from sqlmodel import Field, SQLModel

from .authz import ROLES
from .orgs import ORG_SLUG_SQL_CHECK, validate_org_slug
from .projects import validate_slug

AGENTS: tuple[str, ...] = ("claude", "cursor", "vscode", "codex")
"""Agents ``project_agents.agent`` accepts (the four ``whygraph.agents`` keys)."""

PROJECT_SOURCES: tuple[str, ...] = ("local", "github")
SECRET_KINDS: tuple[str, ...] = ("llm_api_key", "github_token", "claude_oauth_token")
SCAN_KINDS: tuple[str, ...] = ("scan", "sync")
SCAN_TRIGGERS: tuple[str, ...] = (
    "initial",
    "manual",
    "describe",
    "hook",
    "poll",
    "sync",
)
SCAN_STATUSES: tuple[str, ...] = (
    "queued",
    "running",
    "ok",
    "failed",
    "interrupted",
    "cancelled",
)


def _in(column: str, values: tuple[str, ...]) -> str:
    quoted = ", ".join(f"'{v}'" for v in values)
    return f"{column} IN ({quoted})"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _uid() -> str:
    return str(uuid.uuid4())


class PortalBase(SQLModel, registry=registry(metadata=MetaData())):
    """Declarative base of the portal tables; owns the portal ``MetaData``.

    Notes
    -----
    Use ``PortalBase.metadata`` (never ``SQLModel.metadata``) as the
    Alembic ``target_metadata`` for the portal chain.
    """


class Setting(PortalBase, table=True):
    """The single ``settings`` row (``CHECK (id = 1)``).

    Attributes
    ----------
    id : int
        Always ``1``.
    mode : str
        ``"local"`` or ``"production"`` (M2). Chosen at first start,
        never switchable from the web.
    created_at : str
        ISO-8601 UTC timestamp.
    schema_version : str or None
        Free-form portal schema label.
    builtin_org_id : int or None
        The built-in organization of local mode
        (:func:`whygraph.portal.orgs.ensure_builtin_org`); ``NULL`` in
        production. A singleton row makes "at most one built-in org" hold
        for free.
    """

    __tablename__ = "settings"
    __table_args__ = (
        CheckConstraint("id = 1", name="ck_settings_singleton"),
        CheckConstraint(_in("mode", ("local", "production")), name="ck_settings_mode"),
        ForeignKeyConstraint(
            ["builtin_org_id"],
            ["organizations.id"],
            name="fk_settings_builtin_org",
            ondelete="RESTRICT",
        ),
    )

    id: int = Field(default=1, primary_key=True)
    mode: str = Field(default="local", sa_type=Text)
    created_at: str = Field(default_factory=_now, sa_type=Text)
    schema_version: str | None = Field(default=None, sa_type=Text)
    builtin_org_id: int | None = Field(default=None)


class Organization(PortalBase, table=True):
    """An organization: owns projects, config layers and secrets.

    Attributes
    ----------
    uid : str
        Stable UUID4 (what M2e connections reference).
    slug : str
        Immutable; a DNS label (:mod:`whygraph.portal.orgs`), checked on
        insert and by ``ck_organizations_slug``.
    name : str
        Display name.
    created_at : str
        ISO-8601 UTC timestamp.
    """

    __tablename__ = "organizations"
    __table_args__ = (
        UniqueConstraint("uid", name="uq_organizations_uid"),
        UniqueConstraint("slug", name="uq_organizations_slug"),
        CheckConstraint(ORG_SLUG_SQL_CHECK, name="ck_organizations_slug"),
    )

    id: int | None = Field(default=None, primary_key=True)
    uid: str = Field(default_factory=_uid, sa_type=Text)
    slug: str = Field(sa_type=Text)
    name: str = Field(sa_type=Text)
    created_at: str = Field(default_factory=_now, sa_type=Text)


class Membership(PortalBase, table=True):
    """A user's role in one organization.

    Attributes
    ----------
    org_id, user_id : int
        The organization and the user (the primary key).
    role : str
        ``"owner"``, ``"admin"`` or ``"member"``
        (:class:`whygraph.portal.authz.Role`).
    created_at : str
        ISO-8601 UTC timestamp.
    """

    __tablename__ = "memberships"
    __table_args__ = (
        PrimaryKeyConstraint("org_id", "user_id", name="pk_memberships"),
        CheckConstraint(_in("role", ROLES), name="ck_memberships_role"),
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_memberships_org",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_memberships_user",
            ondelete="CASCADE",
        ),
        Index("ix_memberships_user_id", "user_id"),
    )

    org_id: int = Field()
    user_id: int = Field()
    role: str = Field(sa_type=Text)
    created_at: str = Field(default_factory=_now, sa_type=Text)


class User(PortalBase, table=True):
    """A portal user. Local mode has one, created by first-run setup.

    Attributes
    ----------
    uid : str
        Stable UUID4 - what M2 ownership columns reference, so a row
        survives a re-import that changes ``id``.
    display_name : str
        Shown in the UI.
    email : str or None
        The login name in production (M2c), stored normalized (trimmed,
        lowercased; ``ck_users_email_lower`` enforces it). ``NULL`` for
        local mode's email-less user. ``uq_users_email`` is a plain
        unique, so many ``NULL`` values fit.
    password_hash : str or None
        The argon2 hash; ``NULL`` in local mode.
    is_instance_admin : bool
        May use the instance admin page and read every org (M2c).
    password_changed_at : str or None
        ISO-8601 UTC timestamp of the last password change.
    github_id : int or None
        The GitHub numeric user id - the identity of a GitHub account
        (M2d-1); ``NULL`` for password accounts and local mode's user.
    github_login : str or None
        The GitHub username, for display and lookup; unique
        case-insensitively. Refreshed on every sign-in.
    avatar_url : str or None
        From GitHub's profile; refreshed on sign-in.
    disabled_at : str or None
        ISO-8601 UTC timestamp when an instance admin disabled the
        account; ``NULL`` means active.

    Notes
    -----
    A user holds a password **or** a GitHub id, never both
    (``ck_users_one_credential``). A user's role lives in :class:`Membership`, per organization.
    """

    __tablename__ = "users"
    __table_args__ = (
        UniqueConstraint("uid", name="uq_users_uid"),
        UniqueConstraint("email", name="uq_users_email"),
        CheckConstraint("email = lower(email)", name="ck_users_email_lower"),
        UniqueConstraint("github_id", name="uq_users_github_id"),
        Index(
            "uq_users_github_login_lower",
            text("lower(github_login)"),
            unique=True,
        ),
        CheckConstraint(
            "NOT (password_hash IS NOT NULL AND github_id IS NOT NULL)",
            name="ck_users_one_credential",
        ),
        CheckConstraint(
            "github_login IS NULL OR github_id IS NOT NULL",
            name="ck_users_login_needs_id",
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    uid: str = Field(default_factory=_uid, sa_type=Text)
    display_name: str = Field(sa_type=Text)
    email: str | None = Field(default=None, sa_type=Text)
    password_hash: str | None = Field(default=None, sa_type=Text)
    is_instance_admin: bool = Field(default=False)
    password_changed_at: str | None = Field(default=None, sa_type=Text)
    github_id: int | None = Field(default=None, sa_type=BigInteger)
    github_login: str | None = Field(default=None, sa_type=Text)
    avatar_url: str | None = Field(default=None, sa_type=Text)
    disabled_at: str | None = Field(default=None, sa_type=Text)
    created_at: str = Field(default_factory=_now, sa_type=Text)


class UserSession(PortalBase, table=True):
    """A signed-in browser session (M2c); named to avoid SQLModel's ``Session``.

    Attributes
    ----------
    token_hash : str
        SHA-256 of the cookie token; the token itself is never stored.
    user_id : int
        The signed-in user; the row goes with the user.
    created_at, last_seen_at, expires_at : str
        ISO-8601 UTC timestamps (``expires_at`` is the absolute lifetime).
    user_agent : str or None
        The first 200 characters of the ``User-Agent`` header.
    """

    __tablename__ = "sessions"
    __table_args__ = (
        UniqueConstraint("token_hash", name="uq_sessions_token_hash"),
        ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_sessions_user",
            ondelete="CASCADE",
        ),
        Index("ix_sessions_user_id", "user_id"),
    )

    id: int | None = Field(default=None, primary_key=True)
    token_hash: str = Field(sa_type=Text)
    user_id: int = Field()
    created_at: str = Field(default_factory=_now, sa_type=Text)
    last_seen_at: str = Field(default_factory=_now, sa_type=Text)
    expires_at: str = Field(sa_type=Text)
    user_agent: str | None = Field(default=None, sa_type=Text)


class PasswordReset(PortalBase, table=True):
    """A one-time password reset link an instance admin issued (M2c).

    Attributes
    ----------
    token_hash : str
        SHA-256 of the link's token.
    user_id : int
        The user the link resets; the row goes with the user.
    created_by : int or None
        The issuing admin's ``users.id``; ``NULL`` when that user is gone.
    created_at, expires_at : str
        ISO-8601 UTC timestamps.
    used_at : str or None
        When the link was used; ``NULL`` while unused.
    """

    __tablename__ = "password_resets"
    __table_args__ = (
        UniqueConstraint("token_hash", name="uq_password_resets_token_hash"),
        ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_password_resets_user",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_password_resets_created_by",
            ondelete="SET NULL",
        ),
        Index("ix_password_resets_user_id", "user_id"),
    )

    id: int | None = Field(default=None, primary_key=True)
    token_hash: str = Field(sa_type=Text)
    user_id: int = Field()
    created_by: int | None = Field(default=None)
    created_at: str = Field(default_factory=_now, sa_type=Text)
    expires_at: str = Field(sa_type=Text)
    used_at: str | None = Field(default=None, sa_type=Text)


class Project(PortalBase, table=True):
    """A registered project.

    Attributes
    ----------
    org_id : int
        The owning organization; immutable (a project never moves).
    slug : str
        Immutable identity, unique within its organization (see
        :mod:`whygraph.portal.projects`).
    name : str
        Display name; the only renamable field.
    source : str
        ``"local"`` (a shared-folder repo mounted in place) or
        ``"github"`` (cloned by the portal under the data dir).
    root : str
        Absolute path for a local repo; relative to the data dir
        (``repos/<slug>``) for a GitHub clone.
    remote_url : str or None
        Git remote URL, when known.
    initialized_at, last_scan_at, last_scanned_head : str or None
        Lifecycle timestamps and the HEAD of the last successful scan.
    created_by : int or None
        ``users.id`` (M2 audit); ``NULL`` when the user is gone.
    """

    __tablename__ = "projects"
    __table_args__ = (
        UniqueConstraint("org_id", "slug", name="uq_projects_org_slug"),
        # The target of the composite (org_id, project_id) foreign keys.
        UniqueConstraint("org_id", "id", name="uq_projects_org_id"),
        UniqueConstraint("root", name="uq_projects_root"),
        CheckConstraint(_in("source", PROJECT_SOURCES), name="ck_projects_source"),
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_projects_org",
            ondelete="RESTRICT",
        ),
        ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_projects_created_by",
            ondelete="SET NULL",
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    org_id: int = Field()
    slug: str = Field(sa_type=Text)
    name: str = Field(sa_type=Text)
    source: str = Field(sa_type=Text)
    root: str = Field(sa_type=Text)
    remote_url: str | None = Field(default=None, sa_type=Text)
    initialized_at: str | None = Field(default=None, sa_type=Text)
    last_scan_at: str | None = Field(default=None, sa_type=Text)
    last_scanned_head: str | None = Field(default=None, sa_type=Text)
    created_by: int | None = Field(default=None)
    created_at: str = Field(default_factory=_now, sa_type=Text)


class ProjectAgent(PortalBase, table=True):
    """One agent whose MCP config ``initialize`` wrote for a project."""

    __tablename__ = "project_agents"
    __table_args__ = (
        PrimaryKeyConstraint("project_id", "agent", name="pk_project_agents"),
        CheckConstraint(_in("agent", AGENTS), name="ck_project_agents_agent"),
        ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_project_agents_project",
            ondelete="CASCADE",
        ),
    )

    project_id: int = Field()
    agent: str = Field(sa_type=Text)
    configured_at: str = Field(default_factory=_now, sa_type=Text)


class ProjectConfig(PortalBase, table=True):
    """A config v2 layer: an org's defaults (``project_id`` NULL) or one project's.

    ``config`` never holds a secret (:mod:`whygraph.portal.config_layers`
    rejects ``api_key`` / ``token``). Uniqueness is one ``UNIQUE (org_id,
    project_id) NULLS NOT DISTINCT`` constraint: one row per project and
    exactly one org-defaults row per org - a plain ``UNIQUE`` would let
    repeated saves of the defaults duplicate the row, because ``NULL``
    values are distinct by default. The composite foreign key refuses a
    project row filed under another org.
    """

    __tablename__ = "project_config"
    __table_args__ = (
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_project_config_org",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["org_id", "project_id"],
            ["projects.org_id", "projects.id"],
            name="fk_project_config_project",
            ondelete="CASCADE",
        ),
        UniqueConstraint(
            "org_id",
            "project_id",
            name="uq_project_config_scope",
            postgresql_nulls_not_distinct=True,
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    org_id: int = Field()
    project_id: int | None = Field(default=None)
    config: dict[str, Any] = Field(
        default_factory=dict, sa_column=Column(JSON, nullable=False)
    )
    updated_at: str = Field(default_factory=_now, sa_type=Text)


class Secret(PortalBase, table=True):
    """An encrypted secret, an org default (``project_id`` NULL) or per project.

    Attributes
    ----------
    org_id : int
        The owning organization.
    kind : str
        ``"llm_api_key"`` (``provider`` set) or ``"github_token"``
        (``provider`` NULL).
    ciphertext : str
        Fernet token (:mod:`whygraph.portal.secrets`).
    hint : str
        ``"...a1b2"``-style last four characters, for display only.
    created_at : str
        When the current value was written (a re-save replaces the value
        in place and refreshes this).

    Notes
    -----
    Uniqueness is one ``UNIQUE (org_id, project_id, kind, provider) NULLS
    NOT DISTINCT`` constraint: ``project_id`` is NULL for an org-default
    secret and ``provider`` is NULL for a GitHub or Claude OAuth token, and
    each NULL must count as one value, not as distinct ones. The composite
    foreign key refuses a project secret filed under another org.
    """

    __tablename__ = "secrets"
    __table_args__ = (
        CheckConstraint(_in("kind", SECRET_KINDS), name="ck_secrets_kind"),
        CheckConstraint(
            "(kind = 'llm_api_key') = (provider IS NOT NULL)",
            name="ck_secrets_provider",
        ),
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_secrets_org",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["org_id", "project_id"],
            ["projects.org_id", "projects.id"],
            name="fk_secrets_project",
            ondelete="CASCADE",
        ),
        UniqueConstraint(
            "org_id",
            "project_id",
            "kind",
            "provider",
            name="uq_secrets_scope",
            postgresql_nulls_not_distinct=True,
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    org_id: int = Field()
    project_id: int | None = Field(default=None)
    kind: str = Field(sa_type=Text)
    provider: str | None = Field(default=None, sa_type=Text)
    ciphertext: str = Field(sa_type=Text)
    hint: str = Field(sa_type=Text)
    created_at: str = Field(default_factory=_now, sa_type=Text)


class ScanRun(PortalBase, table=True):
    """One scan (or GitHub sync) run of a project (written by the runner, step 8).

    Attributes
    ----------
    kind : str
        ``"scan"`` or ``"sync"``.
    trigger : str
        ``"initial"``, ``"manual"``, ``"describe"``, ``"hook"``,
        ``"poll"`` or ``"sync"``.
    analyze : bool
        Whether the run describes commits (resolved from the trigger).
    requested_by : int or None
        ``users.id``; ``NULL`` for hook / poll / catch-up runs.
    status : str
        ``queued``, ``running``, ``ok``, ``failed``, ``interrupted`` or
        ``cancelled``.
    events_path, log_path : str or None
        Relative to the data dir (``runs/42.jsonl``).
    summary : str or None
        JSON-encoded result summary. While a ``sync`` row is queued it holds
        ``{"scan_requested": true}`` when a scan was merged into it, so a
        restart does not drop that scan.
    """

    __tablename__ = "scan_runs"
    __table_args__ = (
        CheckConstraint(_in("kind", SCAN_KINDS), name="ck_scan_runs_kind"),
        CheckConstraint(_in("trigger", SCAN_TRIGGERS), name="ck_scan_runs_trigger"),
        CheckConstraint(_in("status", SCAN_STATUSES), name="ck_scan_runs_status"),
        ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_scan_runs_project",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name="fk_scan_runs_requested_by",
            ondelete="SET NULL",
        ),
        Index("ix_scan_runs_project_id", "project_id"),
    )

    id: int | None = Field(default=None, primary_key=True)
    project_id: int = Field()
    kind: str = Field(default="scan", sa_type=Text)
    trigger: str = Field(sa_type=Text)
    analyze: bool = Field(default=True, sa_column=Column(Boolean, nullable=False))
    requested_by: int | None = Field(default=None)
    status: str = Field(default="queued", sa_type=Text)
    started_at: str | None = Field(default=None, sa_type=Text)
    finished_at: str | None = Field(default=None, sa_type=Text)
    events_path: str | None = Field(default=None, sa_type=Text)
    log_path: str | None = Field(default=None, sa_type=Text)
    summary: str | None = Field(default=None, sa_type=Text)


@event.listens_for(Project, "before_insert")
def _validate_slug_on_insert(mapper, connection, target: Project) -> None:  # noqa: ANN001
    """Reject a slug that breaks :data:`whygraph.portal.projects.SLUG_RE`."""
    validate_slug(target.slug)


@event.listens_for(Project, "before_update")
def _slug_is_immutable(mapper, connection, target: Project) -> None:  # noqa: ANN001
    """Refuse to change a flushed project's slug or org (only ``name`` is renamable)."""
    attrs = inspect(target).attrs
    if attrs.slug.history.has_changes():
        raise ValueError("a project's slug is immutable; rename only its name")
    if attrs.org_id.history.has_changes():
        raise ValueError("a project's organization is immutable")


@event.listens_for(Organization, "before_insert")
def _validate_org_slug_on_insert(mapper, connection, target: Organization) -> None:  # noqa: ANN001
    """Reject a slug that breaks the rules of :mod:`whygraph.portal.orgs`."""
    validate_org_slug(target.slug)


@event.listens_for(Organization, "before_update")
def _org_slug_is_immutable(mapper, connection, target: Organization) -> None:  # noqa: ANN001
    """Refuse to change a flushed organization's slug."""
    if inspect(target).attrs.slug.history.has_changes():
        raise ValueError("an organization's slug is immutable; rename only its name")


__all__ = [
    "AGENTS",
    "Membership",
    "Organization",
    "PasswordReset",
    "PortalBase",
    "Project",
    "ProjectAgent",
    "ProjectConfig",
    "ScanRun",
    "Secret",
    "Setting",
    "User",
    "UserSession",
]
