"""SQLModel tables of the portal database.

Every table is declared on :class:`PortalBase`, whose ``MetaData`` is its
own - **not** :data:`sqlmodel.SQLModel.metadata`. Portal tables on the
global metadata would be seen as "known" by the project ``env.py``
``include_object`` filter (``whygraph/db/migrations/env.py``) and could be
autogenerated into *project* migrations. The reverse holds too: portal
Alembic never sees a project table. A test pins both directions.

Every model sets an explicit ``__tablename__`` (a model written like the
project ones, on :class:`whygraph.db.base.WhygraphTable`, would land on
the global metadata) and every constraint is named, so a migration
can address it.

Conventions match :mod:`whygraph.db.models`: text columns are ``TEXT``,
timestamps are ISO-8601 UTC strings. ``project_config.config`` is a real
JSON column. Paths that point inside the data directory
(``projects.root`` of a GitHub clone, ``scan_runs.*_path``) are stored
**relative** to it, so a data directory can be moved.

Notes
-----
``settings.schema_version`` is called ``schema`` in the design; the
attribute would shadow pydantic's ``BaseModel.schema``.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    ForeignKeyConstraint,
    Index,
    MetaData,
    Numeric,
    PrimaryKeyConstraint,
    SmallInteger,
    Text,
    UniqueConstraint,
    event,
    inspect,
    text,
)
from sqlalchemy.orm import registry
from sqlmodel import Field, SQLModel

from .authz import DEFAULT_PROJECT_ROLES, PROJECT_ROLES, ROLES
from .orgs import ORG_SLUG_SQL_CHECK, validate_org_slug
from .projects import validate_slug

AGENTS: tuple[str, ...] = ("claude", "cursor", "vscode", "codex")
"""Agents ``project_agents.agent`` accepts (the four ``whygraph.agents`` keys)."""

PROJECT_SOURCES: tuple[str, ...] = ("local", "github", "platform")
REVOKED_REASONS: tuple[str, ...] = (
    "user_revoked",
    "admin_revoked",
    "removed_locally",
    "member_removed",
    "member_left",
    "user_disabled",
    "project_deleted",
    "org_deleted",
    "idle",
    "project_access_removed",
)
"""Why a connection token was revoked (``connection_tokens.revoked_reason``)."""
LINK_STATUSES: tuple[str, ...] = (
    "ok",
    "unreachable",
    "revoked",
    "removed",
    "access_lost",
    "update_required",
)
"""What a local portal last saw of a linked project (``platform_links.status``)."""
SECRET_KINDS: tuple[str, ...] = ("llm_api_key", "github_token")
SCAN_KINDS: tuple[str, ...] = ("scan", "sync")
SCAN_TRIGGERS: tuple[str, ...] = (
    "initial",
    "manual",
    "describe",
    "hook",
    "poll",
    "sync",
    "push",
    "reconcile",
)
SCAN_STATUSES: tuple[str, ...] = (
    "queued",
    "running",
    "ok",
    "failed",
    "interrupted",
    "cancelled",
)
USAGE_SOURCES: tuple[str, ...] = ("scan", "explorer", "chat", "mcp", "agent")
"""What caused an LLM call (``usage_events.source``); every source but
``scan`` is interactive."""
USAGE_TASKS: tuple[str, ...] = ("analyze", "rationale", "chat")
"""The task an LLM call served (``usage_events.task``)."""
KEY_SCOPES: tuple[str, ...] = ("project", "org", "environment", "none")
"""Whose key paid for an LLM call (``usage_events.key_scope``)."""
COST_SOURCES: tuple[str, ...] = ("provider", "estimated", "unpriced")
"""Where a call's cost came from (``usage_events.cost_source``)."""
AGENT_CALL_SOURCES: tuple[str, ...] = ("mcp", "agent")
"""Who made an agent call (``agent_call_days.source``)."""
BUDGET_SCOPES: tuple[str, ...] = ("org", "project", "member_default", "member")
"""What a monthly budget caps (``budgets.scope``)."""
BUDGET_THRESHOLDS: tuple[int, ...] = (50, 75, 100)
"""The percentages of a budget at which an alert fires
(``budget_alerts.threshold``)."""


def _in(column: str, values: tuple[str, ...]) -> str:
    quoted = ", ".join(f"'{v}'" for v in values)
    return f"{column} IN ({quoted})"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _uid() -> str:
    return str(uuid.uuid4())


class PortalBase(SQLModel, registry=registry(metadata=MetaData())):
    """Declarative base of the portal tables; owns the portal ``MetaData``.

    Notes
    -----
    Use ``PortalBase.metadata`` (never ``SQLModel.metadata``) as the
    Alembic ``target_metadata`` for the portal chain.
    """


class Setting(PortalBase, table=True):
    """The single ``settings`` row (``CHECK (id = 1)``).

    Attributes
    ----------
    id : int
        Always ``1``.
    mode : str
        ``"local"`` or ``"production"`` (M2). Chosen at first start,
        never switchable from the web.
    created_at : str
        ISO-8601 UTC timestamp.
    schema_version : str or None
        Free-form portal schema label.
    builtin_org_id : int or None
        The built-in organization of local mode
        (:func:`whygraph.portal.orgs.ensure_builtin_org`); ``NULL`` in
        production. A singleton row makes "at most one built-in org" hold
        for free.
    """

    __tablename__ = "settings"
    __table_args__ = (
        CheckConstraint("id = 1", name="ck_settings_singleton"),
        CheckConstraint(_in("mode", ("local", "production")), name="ck_settings_mode"),
        ForeignKeyConstraint(
            ["builtin_org_id"],
            ["organizations.id"],
            name="fk_settings_builtin_org",
            ondelete="RESTRICT",
        ),
    )

    id: int = Field(default=1, primary_key=True)
    mode: str = Field(default="local", sa_type=Text)
    created_at: str = Field(default_factory=_now, sa_type=Text)
    schema_version: str | None = Field(default=None, sa_type=Text)
    builtin_org_id: int | None = Field(default=None)


class Organization(PortalBase, table=True):
    """An organization: owns projects, config layers and secrets.

    Attributes
    ----------
    uid : str
        Stable UUID4 (what M2e connections reference).
    slug : str
        Immutable; a DNS label (:mod:`whygraph.portal.orgs`), checked on
        insert and by ``ck_organizations_slug``.
    name : str
        Display name.
    created_at : str
        ISO-8601 UTC timestamp.
    default_project_role : str
        What a member holds on a project they have no grant on: one of
        :data:`~whygraph.portal.authz.DEFAULT_PROJECT_ROLES`.
    """

    __tablename__ = "organizations"
    __table_args__ = (
        UniqueConstraint("uid", name="uq_organizations_uid"),
        UniqueConstraint("slug", name="uq_organizations_slug"),
        CheckConstraint(ORG_SLUG_SQL_CHECK, name="ck_organizations_slug"),
        CheckConstraint(
            _in("default_project_role", DEFAULT_PROJECT_ROLES),
            name="ck_organizations_default_project_role",
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    uid: str = Field(default_factory=_uid, sa_type=Text)
    slug: str = Field(sa_type=Text)
    name: str = Field(sa_type=Text)
    created_at: str = Field(default_factory=_now, sa_type=Text)
    default_project_role: str = Field(default="contributor", sa_type=Text)


class Membership(PortalBase, table=True):
    """A user's role in one organization.

    Attributes
    ----------
    org_id, user_id : int
        The organization and the user (the primary key).
    role : str
        ``"owner"``, ``"admin"`` or ``"member"``
        (:class:`whygraph.portal.authz.Role`).
    created_at : str
        ISO-8601 UTC timestamp.
    welcome_pending : bool
        ``True`` from joining until the member dismisses the welcome banner.
    """

    __tablename__ = "memberships"
    __table_args__ = (
        PrimaryKeyConstraint("org_id", "user_id", name="pk_memberships"),
        CheckConstraint(_in("role", ROLES), name="ck_memberships_role"),
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_memberships_org",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_memberships_user",
            ondelete="CASCADE",
        ),
        Index("ix_memberships_user_id", "user_id"),
    )

    org_id: int = Field()
    user_id: int = Field()
    role: str = Field(sa_type=Text)
    created_at: str = Field(default_factory=_now, sa_type=Text)
    welcome_pending: bool = Field(
        default=False, sa_column=Column(Boolean, nullable=False)
    )


class User(PortalBase, table=True):
    """A portal user. Local mode has one, created by first-run setup.

    Attributes
    ----------
    uid : str
        Stable UUID4 - what M2 ownership columns reference, so a row
        survives a re-import that changes ``id``.
    display_name : str
        Shown in the UI.
    email : str or None
        The login name in production (M2c), stored normalized (trimmed,
        lowercased; ``ck_users_email_lower`` enforces it). ``NULL`` for
        local mode's email-less user. ``uq_users_email`` is a plain
        unique, so many ``NULL`` values fit.
    password_hash : str or None
        The argon2 hash; ``NULL`` in local mode.
    is_instance_admin : bool
        May use the instance admin page and read every org (M2c).
    password_changed_at : str or None
        ISO-8601 UTC timestamp of the last password change.
    github_id : int or None
        The GitHub numeric user id - the identity of a GitHub account
        (M2d-1); ``NULL`` for password accounts and local mode's user.
    github_login : str or None
        The GitHub username, for display and lookup; unique
        case-insensitively. Refreshed on every sign-in.
    avatar_url : str or None
        From GitHub's profile; refreshed on sign-in.
    disabled_at : str or None
        ISO-8601 UTC timestamp when an instance admin disabled the
        account; ``NULL`` means active.

    Notes
    -----
    A user holds a password **or** a GitHub id, never both
    (``ck_users_one_credential``). A user's role lives in :class:`Membership`, per organization.
    """

    __tablename__ = "users"
    __table_args__ = (
        UniqueConstraint("uid", name="uq_users_uid"),
        UniqueConstraint("email", name="uq_users_email"),
        CheckConstraint("email = lower(email)", name="ck_users_email_lower"),
        UniqueConstraint("github_id", name="uq_users_github_id"),
        Index(
            "uq_users_github_login_lower",
            text("lower(github_login)"),
            unique=True,
        ),
        CheckConstraint(
            "NOT (password_hash IS NOT NULL AND github_id IS NOT NULL)",
            name="ck_users_one_credential",
        ),
        CheckConstraint(
            "github_login IS NULL OR github_id IS NOT NULL",
            name="ck_users_login_needs_id",
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    uid: str = Field(default_factory=_uid, sa_type=Text)
    display_name: str = Field(sa_type=Text)
    email: str | None = Field(default=None, sa_type=Text)
    password_hash: str | None = Field(default=None, sa_type=Text)
    is_instance_admin: bool = Field(default=False)
    password_changed_at: str | None = Field(default=None, sa_type=Text)
    github_id: int | None = Field(default=None, sa_type=BigInteger)
    github_login: str | None = Field(default=None, sa_type=Text)
    avatar_url: str | None = Field(default=None, sa_type=Text)
    disabled_at: str | None = Field(default=None, sa_type=Text)
    created_at: str = Field(default_factory=_now, sa_type=Text)


class UserSession(PortalBase, table=True):
    """A signed-in browser session (M2c); named to avoid SQLModel's ``Session``.

    Attributes
    ----------
    token_hash : str
        SHA-256 of the cookie token; the token itself is never stored.
    user_id : int
        The signed-in user; the row goes with the user.
    created_at, last_seen_at, expires_at : str
        ISO-8601 UTC timestamps (``expires_at`` is the absolute lifetime).
    user_agent : str or None
        The first 200 characters of the ``User-Agent`` header.
    """

    __tablename__ = "sessions"
    __table_args__ = (
        UniqueConstraint("token_hash", name="uq_sessions_token_hash"),
        ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_sessions_user",
            ondelete="CASCADE",
        ),
        Index("ix_sessions_user_id", "user_id"),
    )

    id: int | None = Field(default=None, primary_key=True)
    token_hash: str = Field(sa_type=Text)
    user_id: int = Field()
    created_at: str = Field(default_factory=_now, sa_type=Text)
    last_seen_at: str = Field(default_factory=_now, sa_type=Text)
    expires_at: str = Field(sa_type=Text)
    user_agent: str | None = Field(default=None, sa_type=Text)


class PasswordReset(PortalBase, table=True):
    """A one-time password reset link an instance admin issued (M2c).

    Attributes
    ----------
    token_hash : str
        SHA-256 of the link's token.
    user_id : int
        The user the link resets; the row goes with the user.
    created_by : int or None
        The issuing admin's ``users.id``; ``NULL`` when that user is gone.
    created_at, expires_at : str
        ISO-8601 UTC timestamps.
    used_at : str or None
        When the link was used; ``NULL`` while unused.
    """

    __tablename__ = "password_resets"
    __table_args__ = (
        UniqueConstraint("token_hash", name="uq_password_resets_token_hash"),
        ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_password_resets_user",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_password_resets_created_by",
            ondelete="SET NULL",
        ),
        Index("ix_password_resets_user_id", "user_id"),
    )

    id: int | None = Field(default=None, primary_key=True)
    token_hash: str = Field(sa_type=Text)
    user_id: int = Field()
    created_by: int | None = Field(default=None)
    created_at: str = Field(default_factory=_now, sa_type=Text)
    expires_at: str = Field(sa_type=Text)
    used_at: str | None = Field(default=None, sa_type=Text)


class Project(PortalBase, table=True):
    """A registered project.

    Attributes
    ----------
    org_id : int
        The owning organization; immutable (a project never moves).
    slug : str
        Immutable identity, unique within its organization (see
        :mod:`whygraph.portal.projects`).
    name : str
        Display name; the only renamable field.
    source : str
        ``"local"`` (a shared-folder repo mounted in place), ``"github"``
        (cloned by the portal under the data dir) or ``"platform"`` (a
        local checkout linked to a project on a WhyGraph platform, M2e; see
        :class:`PlatformLink`).
    root : str
        Absolute path for a local repo; relative to the data dir for a
        GitHub clone (``repos/<org slug>/<slug>``; ``repos/<slug>`` for a
        local clone of an earlier build).
    remote_url : str or None
        Git remote URL, when known (display only for an imported repo).
    initialized_at, last_scan_at, last_scanned_head : str or None
        Lifecycle timestamps and the HEAD of the last successful scan.
    created_by : int or None
        ``users.id`` (M2 audit); ``NULL`` when the user is gone.
    github_repo_id : int or None
        GitHub's numeric repository id - the identity of a repo imported
        through the GitHub App (M2d-2); it survives a rename or transfer.
        Unique per org (``uq_projects_org_github_repo``, a partial index
        over the non-``NULL`` ids); ``NULL`` for a local project.
    github_installation_id : int or None
        The GitHub App installation that covers the repo.
    default_branch : str or None
        The repo's default branch as GitHub reports it (the one scanned).
    access_lost_at, access_lost_reason : str or None
        When and why the portal lost access to the repo (app uninstalled,
        repo removed or deleted); ``NULL`` while it has access.
    restricted : bool
        When true only org admins / owners and users with a
        :class:`ProjectGrant` can see the project.
    """

    __tablename__ = "projects"
    __table_args__ = (
        UniqueConstraint("org_id", "slug", name="uq_projects_org_slug"),
        # The target of the composite (org_id, project_id) foreign keys.
        UniqueConstraint("org_id", "id", name="uq_projects_org_id"),
        UniqueConstraint("root", name="uq_projects_root"),
        CheckConstraint(_in("source", PROJECT_SOURCES), name="ck_projects_source"),
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_projects_org",
            ondelete="RESTRICT",
        ),
        ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_projects_created_by",
            ondelete="SET NULL",
        ),
        Index(
            "uq_projects_org_github_repo",
            "org_id",
            "github_repo_id",
            unique=True,
            postgresql_where=text("github_repo_id IS NOT NULL"),
        ),
        Index("ix_projects_github_repo_id", "github_repo_id"),
    )

    id: int | None = Field(default=None, primary_key=True)
    org_id: int = Field()
    slug: str = Field(sa_type=Text)
    name: str = Field(sa_type=Text)
    source: str = Field(sa_type=Text)
    root: str = Field(sa_type=Text)
    remote_url: str | None = Field(default=None, sa_type=Text)
    initialized_at: str | None = Field(default=None, sa_type=Text)
    last_scan_at: str | None = Field(default=None, sa_type=Text)
    last_scanned_head: str | None = Field(default=None, sa_type=Text)
    created_by: int | None = Field(default=None)
    created_at: str = Field(default_factory=_now, sa_type=Text)
    github_repo_id: int | None = Field(default=None, sa_type=BigInteger)
    github_installation_id: int | None = Field(default=None, sa_type=BigInteger)
    default_branch: str | None = Field(default=None, sa_type=Text)
    access_lost_at: str | None = Field(default=None, sa_type=Text)
    access_lost_reason: str | None = Field(default=None, sa_type=Text)
    restricted: bool = Field(default=False, sa_column=Column(Boolean, nullable=False))


class RetiredOrgSlug(PortalBase, table=True):
    """The slug of a deleted organization, never handed out again (M2d-2).

    Attributes
    ----------
    slug : str
        The retired slug (the primary key).
    retired_at : str
        ISO-8601 UTC timestamp of the deletion.
    """

    __tablename__ = "retired_org_slugs"

    slug: str = Field(sa_type=Text, primary_key=True)
    retired_at: str = Field(default_factory=_now, sa_type=Text)


class ProjectAgent(PortalBase, table=True):
    """One agent whose MCP config ``initialize`` wrote for a project."""

    __tablename__ = "project_agents"
    __table_args__ = (
        PrimaryKeyConstraint("project_id", "agent", name="pk_project_agents"),
        CheckConstraint(_in("agent", AGENTS), name="ck_project_agents_agent"),
        ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_project_agents_project",
            ondelete="CASCADE",
        ),
    )

    project_id: int = Field()
    agent: str = Field(sa_type=Text)
    configured_at: str = Field(default_factory=_now, sa_type=Text)


class ProjectConfig(PortalBase, table=True):
    """A config v2 layer: an org's defaults (``project_id`` NULL) or one project's.

    ``config`` never holds a secret (:mod:`whygraph.portal.config_layers`
    rejects ``api_key`` / ``token``). Uniqueness is one ``UNIQUE (org_id,
    project_id) NULLS NOT DISTINCT`` constraint: one row per project and
    exactly one org-defaults row per org - a plain ``UNIQUE`` would let
    repeated saves of the defaults duplicate the row, because ``NULL``
    values are distinct by default. The composite foreign key refuses a
    project row filed under another org.
    """

    __tablename__ = "project_config"
    __table_args__ = (
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_project_config_org",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["org_id", "project_id"],
            ["projects.org_id", "projects.id"],
            name="fk_project_config_project",
            ondelete="CASCADE",
        ),
        UniqueConstraint(
            "org_id",
            "project_id",
            name="uq_project_config_scope",
            postgresql_nulls_not_distinct=True,
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    org_id: int = Field()
    project_id: int | None = Field(default=None)
    config: dict[str, Any] = Field(
        default_factory=dict, sa_column=Column(JSON, nullable=False)
    )
    updated_at: str = Field(default_factory=_now, sa_type=Text)


class Secret(PortalBase, table=True):
    """An encrypted secret, an org default (``project_id`` NULL) or per project.

    Attributes
    ----------
    org_id : int
        The owning organization.
    kind : str
        ``"llm_api_key"`` (``provider`` set) or ``"github_token"``
        (``provider`` NULL).
    ciphertext : str
        Fernet token (:mod:`whygraph.portal.secrets`).
    hint : str
        ``"...a1b2"``-style last four characters, for display only.
    created_at : str
        When the current value was written (a re-save replaces the value
        in place and refreshes this).

    Notes
    -----
    Uniqueness is one ``UNIQUE (org_id, project_id, kind, provider) NULLS
    NOT DISTINCT`` constraint: ``project_id`` is NULL for an org-default
    secret and ``provider`` is NULL for a GitHub token, and
    each NULL must count as one value, not as distinct ones. The composite
    foreign key refuses a project secret filed under another org.
    """

    __tablename__ = "secrets"
    __table_args__ = (
        CheckConstraint(_in("kind", SECRET_KINDS), name="ck_secrets_kind"),
        CheckConstraint(
            "(kind = 'llm_api_key') = (provider IS NOT NULL)",
            name="ck_secrets_provider",
        ),
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_secrets_org",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["org_id", "project_id"],
            ["projects.org_id", "projects.id"],
            name="fk_secrets_project",
            ondelete="CASCADE",
        ),
        UniqueConstraint(
            "org_id",
            "project_id",
            "kind",
            "provider",
            name="uq_secrets_scope",
            postgresql_nulls_not_distinct=True,
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    org_id: int = Field()
    project_id: int | None = Field(default=None)
    kind: str = Field(sa_type=Text)
    provider: str | None = Field(default=None, sa_type=Text)
    ciphertext: str = Field(sa_type=Text)
    hint: str = Field(sa_type=Text)
    created_at: str = Field(default_factory=_now, sa_type=Text)


class ScanRun(PortalBase, table=True):
    """One scan (or GitHub sync) run of a project (written by the runner, step 8).

    Attributes
    ----------
    kind : str
        ``"scan"`` or ``"sync"``.
    trigger : str
        ``"initial"``, ``"manual"``, ``"describe"``, ``"hook"``,
        ``"poll"``, ``"sync"``, ``"push"`` (a GitHub webhook) or
        ``"reconcile"`` (the periodic remote-head check).
    analyze : bool
        Whether the run describes commits (resolved from the trigger).
    requested_by : int or None
        ``users.id``; ``NULL`` for hook / poll / catch-up runs.
    status : str
        ``queued``, ``running``, ``ok``, ``failed``, ``interrupted`` or
        ``cancelled``.
    events_path, log_path : str or None
        Relative to the data dir (``runs/42.jsonl``).
    summary : str or None
        JSON-encoded result summary. While a ``sync`` row is queued it holds
        ``{"scan_requested": true}`` when a scan was merged into it, so a
        restart does not drop that scan.
    queued_at : str or None
        ISO-8601 UTC timestamp when the run was queued; ``NULL`` on rows
        older than the ux revision.
    cancelled_by : int or None
        ``users.id`` of the member who cancelled the run; ``NULL`` for a
        budget stop, a system cancel or an old row.
    """

    __tablename__ = "scan_runs"
    __table_args__ = (
        CheckConstraint(_in("kind", SCAN_KINDS), name="ck_scan_runs_kind"),
        CheckConstraint(_in("trigger", SCAN_TRIGGERS), name="ck_scan_runs_trigger"),
        CheckConstraint(_in("status", SCAN_STATUSES), name="ck_scan_runs_status"),
        ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_scan_runs_project",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name="fk_scan_runs_requested_by",
            ondelete="SET NULL",
        ),
        ForeignKeyConstraint(
            ["cancelled_by"],
            ["users.id"],
            name="fk_scan_runs_cancelled_by",
            ondelete="SET NULL",
        ),
        Index("ix_scan_runs_project_id", "project_id"),
    )

    id: int | None = Field(default=None, primary_key=True)
    project_id: int = Field()
    kind: str = Field(default="scan", sa_type=Text)
    trigger: str = Field(sa_type=Text)
    analyze: bool = Field(default=True, sa_column=Column(Boolean, nullable=False))
    requested_by: int | None = Field(default=None)
    status: str = Field(default="queued", sa_type=Text)
    started_at: str | None = Field(default=None, sa_type=Text)
    finished_at: str | None = Field(default=None, sa_type=Text)
    events_path: str | None = Field(default=None, sa_type=Text)
    log_path: str | None = Field(default=None, sa_type=Text)
    summary: str | None = Field(default=None, sa_type=Text)
    queued_at: str | None = Field(default=None, sa_type=Text)
    cancelled_by: int | None = Field(default=None)


class ConnectionToken(PortalBase, table=True):
    """A connection token: a local portal acting as one user on one project (M2e).

    Used in production (:mod:`whygraph.portal.connections`); the table exists
    in both modes (one schema).

    Attributes
    ----------
    uid : str
        Stable UUID4 - what the Connected-portals lists and the security log
        name (never ``id``, never the token).
    user_id : int
        The user the token acts as; the row goes with the user.
    org_id, project_id : int or None
        The one project the token reaches, and its org. Set to ``NULL`` when
        the org / project is deleted (the row then answers ``token_revoked``
        until the sweep removes it).
    token_hash : str
        SHA-256 hex of the raw ``wgc_...`` token; the token is never stored.
    client_name : str
        The connected portal's name (``[A-Za-z0-9._ -]{1,64}``).
    created_at : str
        ISO-8601 UTC timestamp.
    last_used_at : str or None
        When the token last authenticated a request; ``NULL`` = never used.
    revoked_at, revoked_reason : str or None
        When and why the token was revoked (one of :data:`REVOKED_REASONS`);
        ``NULL`` while it is live.
    """

    __tablename__ = "connection_tokens"
    __table_args__ = (
        UniqueConstraint("uid", name="uq_connection_tokens_uid"),
        UniqueConstraint("token_hash", name="uq_connection_tokens_token_hash"),
        CheckConstraint(
            _in("revoked_reason", REVOKED_REASONS),
            name="ck_connection_tokens_revoked_reason",
        ),
        ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_connection_tokens_user",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_connection_tokens_org",
            ondelete="SET NULL",
        ),
        ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_connection_tokens_project",
            ondelete="SET NULL",
        ),
        Index("ix_connection_tokens_user_id", "user_id"),
        Index(
            "ix_connection_tokens_live_project_id",
            "project_id",
            postgresql_where=text("revoked_at IS NULL"),
        ),
    )

    id: int | None = Field(default=None, primary_key=True, sa_type=BigInteger)
    uid: str = Field(default_factory=_uid, sa_type=Text)
    user_id: int = Field()
    org_id: int | None = Field(default=None)
    project_id: int | None = Field(default=None)
    token_hash: str = Field(sa_type=Text)
    client_name: str = Field(sa_type=Text)
    created_at: str = Field(default_factory=_now, sa_type=Text)
    last_used_at: str | None = Field(default=None, sa_type=Text)
    revoked_at: str | None = Field(default=None, sa_type=Text)
    revoked_reason: str | None = Field(default=None, sa_type=Text)


class PlatformLink(PortalBase, table=True):
    """A local project linked to a project on a WhyGraph platform (M2e, local mode).

    One row per ``source = 'platform'`` project; it goes with the project.

    Attributes
    ----------
    project_id : int
        The local ``projects.id`` (the primary key).
    platform_origin : str
        The platform's base-host origin, e.g. ``https://whygraph.example``.
    api_origin : str
        Computed locally: ``<scheme>://<org>.<platform host>[:port]``.
    org_slug, remote_slug, remote_name : str
        The platform org, and the project's slug and name there.
    clone_url : str
        The platform project's clone URL (its GitHub host), for matching a
        checkout and for the hint.
    default_branch : str
        The platform project's default branch.
    token_ciphertext : str
        The connection token, encrypted (:func:`whygraph.portal.secrets.encrypt`).
    token_hint : str
        The token's last characters, for display only.
    status : str
        One of :data:`LINK_STATUSES`.
    status_reason : str or None
        The platform's reason, e.g. a ``revoked_reason``.
    status_at : str
        ISO-8601 UTC timestamp of the last status change.
    last_platform_head : str or None
        The platform's ``last_scanned_head`` as last seen.
    remote_project_role : str or None
        The caller's role on the platform project, as the platform last
        reported it; ``NULL`` until seen.
    """

    __tablename__ = "platform_links"
    __table_args__ = (
        CheckConstraint(_in("status", LINK_STATUSES), name="ck_platform_links_status"),
        ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_platform_links_project",
            ondelete="CASCADE",
        ),
    )

    project_id: int = Field(primary_key=True, sa_column_kwargs={"autoincrement": False})
    platform_origin: str = Field(sa_type=Text)
    api_origin: str = Field(sa_type=Text)
    org_slug: str = Field(sa_type=Text)
    remote_slug: str = Field(sa_type=Text)
    remote_name: str = Field(sa_type=Text)
    clone_url: str = Field(sa_type=Text)
    default_branch: str = Field(sa_type=Text)
    token_ciphertext: str = Field(sa_type=Text)
    token_hint: str = Field(sa_type=Text)
    status: str = Field(default="ok", sa_type=Text)
    status_reason: str | None = Field(default=None, sa_type=Text)
    status_at: str = Field(default_factory=_now, sa_type=Text)
    last_platform_head: str | None = Field(default=None, sa_type=Text)
    remote_project_role: str | None = Field(default=None, sa_type=Text)


class ProjectGrant(PortalBase, table=True):
    """A per-user override of the default project role on one project (M2f-1).

    A grant replaces the org default for that user (it can lower as well as
    raise). It goes with the project and with the user's membership.

    Attributes
    ----------
    org_id, project_id, user_id : int
        The organization, the project (in it) and the member; the primary
        key is ``(project_id, user_id)``.
    role : str
        One of :data:`~whygraph.portal.authz.PROJECT_ROLES`.
    granted_by : int or None
        ``users.id`` of the granter; ``NULL`` when that user is gone.
    created_at : str
        ISO-8601 UTC timestamp.
    """

    __tablename__ = "project_grants"
    __table_args__ = (
        PrimaryKeyConstraint("project_id", "user_id", name="pk_project_grants"),
        CheckConstraint(_in("role", PROJECT_ROLES), name="ck_project_grants_role"),
        ForeignKeyConstraint(
            ["org_id", "project_id"],
            ["projects.org_id", "projects.id"],
            name="fk_project_grants_project",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["org_id", "user_id"],
            ["memberships.org_id", "memberships.user_id"],
            name="fk_project_grants_membership",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
            name="fk_project_grants_granted_by",
            ondelete="SET NULL",
        ),
        Index("ix_project_grants_user_id", "user_id"),
    )

    org_id: int = Field()
    project_id: int = Field()
    user_id: int = Field()
    role: str = Field(sa_type=Text)
    granted_by: int | None = Field(default=None)
    created_at: str = Field(default_factory=_now, sa_type=Text)


class Invitation(PortalBase, table=True):
    """An invitation of a GitHub user to an organization (M2f-1).

    Attributes
    ----------
    uid : str
        Stable UUID4.
    org_id : int
        The inviting organization.
    github_id : int
        GitHub's numeric user id - the identity an invitation is matched by.
    github_login : str
        The login as GitHub returned it; display only.
    role : str
        One of :data:`~whygraph.portal.authz.ROLES`.
    invited_by, redeemed_by : int or None
        ``users.id``; ``NULL`` when the user is gone or nobody redeemed yet.
    created_at, expires_at : str
        ISO-8601 UTC timestamps.
    redeemed_at, revoked_at : str or None
        Set when the invitation is closed; at most one open invitation
        exists per ``(org_id, github_id)``.
    """

    __tablename__ = "invitations"
    __table_args__ = (
        UniqueConstraint("uid", name="uq_invitations_uid"),
        # The target of invitation_grants' composite foreign key.
        UniqueConstraint("org_id", "id", name="uq_invitations_org_id"),
        CheckConstraint(_in("role", ROLES), name="ck_invitations_role"),
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_invitations_org",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
            name="fk_invitations_invited_by",
            ondelete="SET NULL",
        ),
        ForeignKeyConstraint(
            ["redeemed_by"],
            ["users.id"],
            name="fk_invitations_redeemed_by",
            ondelete="SET NULL",
        ),
        Index(
            "uq_invitations_open",
            "org_id",
            "github_id",
            unique=True,
            postgresql_where=text("redeemed_at IS NULL AND revoked_at IS NULL"),
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    uid: str = Field(default_factory=_uid, sa_type=Text)
    org_id: int = Field()
    github_id: int = Field(sa_type=BigInteger)
    github_login: str = Field(sa_type=Text)
    role: str = Field(sa_type=Text)
    invited_by: int | None = Field(default=None)
    created_at: str = Field(default_factory=_now, sa_type=Text)
    expires_at: str = Field(sa_type=Text)
    redeemed_at: str | None = Field(default=None, sa_type=Text)
    revoked_at: str | None = Field(default=None, sa_type=Text)
    redeemed_by: int | None = Field(default=None)


class InvitationGrant(PortalBase, table=True):
    """A project grant an invitation carries, applied when it is redeemed (M2f-1).

    Attributes
    ----------
    invitation_id, project_id : int
        The invitation and the project (the primary key).
    org_id : int
        The organization both belong to (composite foreign keys tie them).
    role : str
        One of :data:`~whygraph.portal.authz.PROJECT_ROLES`.
    """

    __tablename__ = "invitation_grants"
    __table_args__ = (
        PrimaryKeyConstraint(
            "invitation_id", "project_id", name="pk_invitation_grants"
        ),
        CheckConstraint(_in("role", PROJECT_ROLES), name="ck_invitation_grants_role"),
        ForeignKeyConstraint(
            ["org_id", "invitation_id"],
            ["invitations.org_id", "invitations.id"],
            name="fk_invitation_grants_invitation",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["org_id", "project_id"],
            ["projects.org_id", "projects.id"],
            name="fk_invitation_grants_project",
            ondelete="CASCADE",
        ),
    )

    invitation_id: int = Field()
    org_id: int = Field()
    project_id: int = Field()
    role: str = Field(sa_type=Text)


class AuditEvent(PortalBase, table=True):
    """One persisted security event (M2f-1, written by the audit writer).

    Attributes
    ----------
    created_at : str
        ISO-8601 UTC timestamp.
    org_id : int or None
        The organization; ``NULL`` for org-less events or a deleted org.
    org_slug : str or None
        Snapshot of the org slug, so a deleted org's events stay readable.
    actor_id : int or None
        ``users.id`` of the actor; ``NULL`` when none or the user is gone.
    actor_label : str or None
        Snapshot of how the actor was named (``@login`` or an email).
    event : str
        The event name.
    target : str or None
        What the event is about.
    ip : str or None
        The client address, when known.
    fields : dict
        Already-redacted extra fields.
    """

    __tablename__ = "audit_events"
    __table_args__ = (
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_audit_events_org",
            ondelete="SET NULL",
        ),
        ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name="fk_audit_events_actor",
            ondelete="SET NULL",
        ),
        Index("ix_audit_events_org_id_id", "org_id", text("id DESC")),
        Index("ix_audit_events_event", "event"),
    )

    id: int | None = Field(default=None, primary_key=True, sa_type=BigInteger)
    created_at: str = Field(default_factory=_now, sa_type=Text)
    org_id: int | None = Field(default=None)
    org_slug: str | None = Field(default=None, sa_type=Text)
    actor_id: int | None = Field(default=None)
    actor_label: str | None = Field(default=None, sa_type=Text)
    event: str = Field(sa_type=Text)
    target: str | None = Field(default=None, sa_type=Text)
    ip: str | None = Field(default=None, sa_type=Text)
    fields: dict[str, Any] = Field(
        default_factory=dict, sa_column=Column(JSON, nullable=False)
    )


class UsageEvent(PortalBase, table=True):
    """One successful LLM provider round trip (M2f-2, the usage ledger).

    Holds counts, cost, model, ids and a short subject - never prompt or
    completion text, never chat content. The labels are snapshots, so a row
    stays readable after its project, member or connection is gone.

    Attributes
    ----------
    id : int
        Serial ``BIGINT`` primary key.
    org_id : int
        The organization; the row goes with it.
    project_id : int or None
        The project; ``NULL`` once the project is deleted.
    project_slug, project_name : str
        Snapshots of the project's slug and name.
    actor_kind : str
        ``"member"`` or ``"system"``. A deleted member's rows keep
        ``"member"`` with ``user_id`` ``NULL``.
    user_id : int or None
        ``users.id`` of the member who triggered the call; always ``NULL``
        for ``"system"``.
    actor_label : str
        Snapshot: ``"Name (@login)"``, ``"Name"`` (local mode) or
        ``"System"``.
    source : str
        One of :data:`USAGE_SOURCES`.
    task : str
        One of :data:`USAGE_TASKS`.
    scan_run_id : int or None
        The scan run that made the call, if any.
    chat_session_id : int or None
        The chat session's id in the project database (no foreign key;
        always read with ``project_id``).
    connection_id : int or None
        The connection token of a linked portal's agent call.
    client_name : str or None
        Snapshot of the connection's ``client_name`` (the machine).
    subject : str or None
        The commit SHA, file path or qualified name the call was about
        (at most 200 characters, redacted).
    provider, model_requested : str
        The provider and the model asked for.
    model_served : str or None
        The model the provider reported, when it did.
    key_scope : str
        One of :data:`KEY_SCOPES`.
    input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens : int or None
        What the provider reported; ``NULL`` = not reported. ``input_tokens``
        counts every prompt token (cache reads and writes included);
        ``cache_*`` are subsets of it and ``reasoning_tokens`` of the output.
    cost_usd : Decimal or None
        The cost, computed once at write time.
    cost_source : str
        One of :data:`COST_SOURCES`.
    price_version : str or None
        The price table the cost came from (``"bundled:<date>"`` or
        ``"org:<updated_at>"``).
    duration_ms : int or None
        How long the provider call took.
    created_at : str
        ISO-8601 UTC timestamp, seconds.
    """

    __tablename__ = "usage_events"
    __table_args__ = (
        CheckConstraint(
            "actor_kind IN ('member', 'system')", name="ck_usage_events_actor_kind"
        ),
        CheckConstraint(_in("source", USAGE_SOURCES), name="ck_usage_events_source"),
        CheckConstraint(_in("task", USAGE_TASKS), name="ck_usage_events_task"),
        CheckConstraint(_in("key_scope", KEY_SCOPES), name="ck_usage_events_key_scope"),
        CheckConstraint(
            _in("cost_source", COST_SOURCES), name="ck_usage_events_cost_source"
        ),
        CheckConstraint(
            "actor_kind <> 'system' OR user_id IS NULL", name="ck_usage_events_actor"
        ),
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_usage_events_org",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_usage_events_project",
            ondelete="SET NULL",
        ),
        ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_usage_events_user",
            ondelete="SET NULL",
        ),
        ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_runs.id"],
            name="fk_usage_events_scan_run",
            ondelete="SET NULL",
        ),
        ForeignKeyConstraint(
            ["connection_id"],
            ["connection_tokens.id"],
            name="fk_usage_events_connection",
            ondelete="SET NULL",
        ),
        Index("ix_usage_events_org_time", "org_id", "created_at"),
        Index("ix_usage_events_org_user_time", "org_id", "user_id", "created_at"),
        Index("ix_usage_events_org_project_time", "org_id", "project_id", "created_at"),
        Index("ix_usage_events_project", "project_id"),
        Index("ix_usage_events_user", "user_id"),
        Index(
            "ix_usage_events_scan_run",
            "scan_run_id",
            postgresql_where=text("scan_run_id IS NOT NULL"),
        ),
        Index(
            "ix_usage_events_connection",
            "connection_id",
            postgresql_where=text("connection_id IS NOT NULL"),
        ),
        Index(
            "ix_usage_events_key_last_used",
            "org_id",
            "provider",
            "key_scope",
            "project_id",
            "created_at",
        ),
    )

    id: int | None = Field(default=None, primary_key=True, sa_type=BigInteger)
    org_id: int = Field()
    project_id: int | None = Field(default=None)
    project_slug: str = Field(sa_type=Text)
    project_name: str = Field(sa_type=Text)
    actor_kind: str = Field(sa_type=Text)
    user_id: int | None = Field(default=None)
    actor_label: str = Field(sa_type=Text)
    source: str = Field(sa_type=Text)
    task: str = Field(sa_type=Text)
    scan_run_id: int | None = Field(default=None)
    chat_session_id: int | None = Field(default=None)
    connection_id: int | None = Field(default=None, sa_type=BigInteger)
    client_name: str | None = Field(default=None, sa_type=Text)
    subject: str | None = Field(default=None, sa_type=Text)
    provider: str = Field(sa_type=Text)
    model_requested: str = Field(sa_type=Text)
    model_served: str | None = Field(default=None, sa_type=Text)
    key_scope: str = Field(sa_type=Text)
    input_tokens: int | None = Field(default=None, sa_type=BigInteger)
    output_tokens: int | None = Field(default=None, sa_type=BigInteger)
    cache_read_tokens: int | None = Field(default=None, sa_type=BigInteger)
    cache_write_tokens: int | None = Field(default=None, sa_type=BigInteger)
    reasoning_tokens: int | None = Field(default=None, sa_type=BigInteger)
    cost_usd: Decimal | None = Field(default=None, sa_type=Numeric(14, 6))
    cost_source: str = Field(sa_type=Text)
    price_version: str | None = Field(default=None, sa_type=Text)
    duration_ms: int | None = Field(default=None)
    created_at: str = Field(default_factory=_now, sa_type=Text)


class AgentCallDay(PortalBase, table=True):
    """One agent-activity counter row (M2f-3).

    Counts the calls of one kind made to one project on one UTC day by one
    caller; the Overview's agent activity and the onboarding "any agent call"
    check read it.

    Attributes
    ----------
    id : int
        Serial ``BIGINT`` primary key.
    org_id, project_id : int
        The project; the row goes with it.
    day : str
        UTC date, ``YYYY-MM-DD``.
    source : str
        One of :data:`AGENT_CALL_SOURCES`.
    user_id : int or None
        The calling member; no foreign key, the counters outlive the user.
    connection_id : int or None
        The connection token that called; no foreign key (the hourly sweep
        deletes tokens).
    kind : str
        The tool or call name, 1 to 64 characters.
    calls : int
        How many calls (always positive).
    """

    __tablename__ = "agent_call_days"
    __table_args__ = (
        CheckConstraint(
            "day ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'", name="ck_agent_call_days_day"
        ),
        CheckConstraint(
            _in("source", AGENT_CALL_SOURCES), name="ck_agent_call_days_source"
        ),
        CheckConstraint(
            "length(kind) BETWEEN 1 AND 64", name="ck_agent_call_days_kind"
        ),
        CheckConstraint("calls > 0", name="ck_agent_call_days_calls"),
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_agent_call_days_org",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["org_id", "project_id"],
            ["projects.org_id", "projects.id"],
            name="fk_agent_call_days_project",
            ondelete="CASCADE",
        ),
        UniqueConstraint(
            "project_id",
            "day",
            "source",
            "user_id",
            "connection_id",
            "kind",
            name="uq_agent_call_days_key",
            postgresql_nulls_not_distinct=True,
        ),
        Index("ix_agent_call_days_org_day", "org_id", "day"),
    )

    id: int | None = Field(default=None, primary_key=True, sa_type=BigInteger)
    org_id: int = Field()
    project_id: int = Field()
    day: str = Field(sa_type=Text)
    source: str = Field(sa_type=Text)
    user_id: int | None = Field(default=None)
    connection_id: int | None = Field(default=None, sa_type=BigInteger)
    kind: str = Field(sa_type=Text)
    calls: int = Field(sa_type=BigInteger)


class Budget(PortalBase, table=True):
    """A monthly LLM spend budget (M2f-2).

    One row per target (``uq_budgets_target``, ``NULLS NOT DISTINCT``): the
    org, a project, the org-wide member default, or one member's override.
    A project budget goes with the project and a member override with the
    membership (composite foreign keys).

    Attributes
    ----------
    org_id : int
        The organization.
    scope : str
        One of :data:`BUDGET_SCOPES`.
    project_id : int or None
        Set exactly when ``scope`` is ``"project"``.
    user_id : int or None
        Set exactly when ``scope`` is ``"member"``.
    monthly_usd : Decimal
        The budget, ``> 0`` and ``<= 1000000``, per calendar month (UTC).
    hard_stop : bool
        Whether an exhausted budget turns off LLM spend for the scope.
    updated_by : int or None
        ``users.id`` of the last writer; ``NULL`` when that user is gone.
    updated_at : str
        ISO-8601 UTC timestamp.
    """

    __tablename__ = "budgets"
    __table_args__ = (
        CheckConstraint(_in("scope", BUDGET_SCOPES), name="ck_budgets_scope"),
        CheckConstraint(
            "monthly_usd > 0 AND monthly_usd <= 1000000", name="ck_budgets_amount"
        ),
        CheckConstraint(
            "(project_id IS NOT NULL) = (scope = 'project') "
            "AND (user_id IS NOT NULL) = (scope = 'member')",
            name="ck_budgets_shape",
        ),
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_budgets_org",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["org_id", "project_id"],
            ["projects.org_id", "projects.id"],
            name="fk_budgets_project",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["org_id", "user_id"],
            ["memberships.org_id", "memberships.user_id"],
            name="fk_budgets_membership",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name="fk_budgets_updated_by",
            ondelete="SET NULL",
        ),
        UniqueConstraint(
            "org_id",
            "scope",
            "project_id",
            "user_id",
            name="uq_budgets_target",
            postgresql_nulls_not_distinct=True,
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    org_id: int = Field()
    scope: str = Field(sa_type=Text)
    project_id: int | None = Field(default=None)
    user_id: int | None = Field(default=None)
    monthly_usd: Decimal = Field(sa_type=Numeric(12, 2))
    hard_stop: bool = Field(default=False, sa_column=Column(Boolean, nullable=False))
    updated_by: int | None = Field(default=None)
    updated_at: str = Field(default_factory=_now, sa_type=Text)


class BudgetAlert(PortalBase, table=True):
    """A budget threshold crossed in one month (M2f-2).

    Each threshold fires once per budget (and, for a ``member_default``
    budget, per member) per month (``uq_budget_alerts_once``).

    Attributes
    ----------
    id : int
        Serial ``BIGINT`` primary key.
    budget_id : int
        The budget; the alert goes with it.
    user_id : int or None
        The member who crossed a ``member_default`` budget; ``NULL`` for
        every other scope.
    month : str
        The calendar month (UTC), ``"2026-10"``.
    threshold : int
        One of :data:`BUDGET_THRESHOLDS`.
    crossed_at : str
        ISO-8601 UTC timestamp.
    spent_usd : Decimal
        The month-to-date spend when the threshold was crossed.
    """

    __tablename__ = "budget_alerts"
    __table_args__ = (
        CheckConstraint(
            "threshold IN (50, 75, 100)", name="ck_budget_alerts_threshold"
        ),
        ForeignKeyConstraint(
            ["budget_id"],
            ["budgets.id"],
            name="fk_budget_alerts_budget",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_budget_alerts_user",
            ondelete="CASCADE",
        ),
        UniqueConstraint(
            "budget_id",
            "user_id",
            "month",
            "threshold",
            name="uq_budget_alerts_once",
            postgresql_nulls_not_distinct=True,
        ),
    )

    id: int | None = Field(default=None, primary_key=True, sa_type=BigInteger)
    budget_id: int = Field()
    user_id: int | None = Field(default=None)
    month: str = Field(sa_type=Text)
    threshold: int = Field(sa_type=SmallInteger)
    crossed_at: str = Field(default_factory=_now, sa_type=Text)
    spent_usd: Decimal = Field(sa_type=Numeric(14, 6))


class PriceOverride(PortalBase, table=True):
    """An org's price for one model, on top of the bundled table (M2f-2).

    Attributes
    ----------
    org_id : int
        The organization.
    provider, model : str
        The model the price is for (with ``org_id``, the primary key).
    input_per_mtok, output_per_mtok : Decimal
        USD per million input / output tokens, ``>= 0``.
    cache_read_per_mtok, cache_write_per_mtok : Decimal or None
        USD per million cache-read / cache-write tokens, ``>= 0``; ``NULL``
        means the input rate.
    updated_by : int or None
        ``users.id`` of the last writer; ``NULL`` when that user is gone.
    updated_at : str
        ISO-8601 UTC timestamp.
    """

    __tablename__ = "price_overrides"
    __table_args__ = (
        PrimaryKeyConstraint("org_id", "provider", "model", name="pk_price_overrides"),
        CheckConstraint(
            "input_per_mtok >= 0 AND output_per_mtok >= 0 "
            "AND (cache_read_per_mtok IS NULL OR cache_read_per_mtok >= 0) "
            "AND (cache_write_per_mtok IS NULL OR cache_write_per_mtok >= 0)",
            name="ck_price_overrides_nonneg",
        ),
        ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="fk_price_overrides_org",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name="fk_price_overrides_updated_by",
            ondelete="SET NULL",
        ),
    )

    org_id: int = Field()
    provider: str = Field(sa_type=Text)
    model: str = Field(sa_type=Text)
    input_per_mtok: Decimal = Field(sa_type=Numeric(12, 6))
    output_per_mtok: Decimal = Field(sa_type=Numeric(12, 6))
    cache_read_per_mtok: Decimal | None = Field(default=None, sa_type=Numeric(12, 6))
    cache_write_per_mtok: Decimal | None = Field(default=None, sa_type=Numeric(12, 6))
    updated_by: int | None = Field(default=None)
    updated_at: str = Field(default_factory=_now, sa_type=Text)


@event.listens_for(Project, "before_insert")
def _validate_slug_on_insert(mapper, connection, target: Project) -> None:  # noqa: ANN001
    """Reject a slug that breaks :data:`whygraph.portal.projects.SLUG_RE`."""
    validate_slug(target.slug)


@event.listens_for(Project, "before_update")
def _slug_is_immutable(mapper, connection, target: Project) -> None:  # noqa: ANN001
    """Refuse to change a flushed project's slug or org (only ``name`` is renamable)."""
    attrs = inspect(target).attrs
    if attrs.slug.history.has_changes():
        raise ValueError("a project's slug is immutable; rename only its name")
    if attrs.org_id.history.has_changes():
        raise ValueError("a project's organization is immutable")


@event.listens_for(Organization, "before_insert")
def _validate_org_slug_on_insert(mapper, connection, target: Organization) -> None:  # noqa: ANN001
    """Reject a slug that breaks the rules of :mod:`whygraph.portal.orgs`."""
    validate_org_slug(target.slug)


@event.listens_for(Organization, "before_update")
def _org_slug_is_immutable(mapper, connection, target: Organization) -> None:  # noqa: ANN001
    """Refuse to change a flushed organization's slug."""
    if inspect(target).attrs.slug.history.has_changes():
        raise ValueError("an organization's slug is immutable; rename only its name")


__all__ = [
    "AGENTS",
    "LINK_STATUSES",
    "PROJECT_SOURCES",
    "REVOKED_REASONS",
    "ConnectionToken",
    "Membership",
    "Organization",
    "PasswordReset",
    "PlatformLink",
    "PortalBase",
    "Project",
    "ProjectAgent",
    "ProjectConfig",
    "RetiredOrgSlug",
    "ScanRun",
    "Secret",
    "Setting",
    "User",
    "UserSession",
]
