"""SQLModel tables of the portal database.

Every table is declared on :class:`PortalBase`, whose ``MetaData`` is its
own - **not** :data:`sqlmodel.SQLModel.metadata`. Portal tables on the
global metadata would be seen as "known" by the project ``env.py``
``include_object`` filter (``whygraph/db/migrations/env.py``) and could be
autogenerated into *project* migrations. The reverse holds too: portal
Alembic never sees a project table. A test pins both directions.

Every model sets an explicit ``__tablename__`` (a model written like the
project ones, on :class:`whygraph.db.base.WhygraphTable`, would land on
the global metadata) and every constraint is named, so a batch migration
can address it.

Conventions match :mod:`whygraph.db.models`: text columns are ``TEXT``,
timestamps are ISO-8601 UTC strings. ``project_config.config`` is a real
JSON column. Paths that point inside the data directory
(``projects.root`` of a GitHub clone, ``scan_runs.*_path``) are stored
**relative** to it, so a data directory can be moved.

Notes
-----
``settings.schema_version`` is called ``schema`` in the design; the
attribute would shadow pydantic's ``BaseModel.schema``.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import (
    JSON,
    Boolean,
    CheckConstraint,
    Column,
    ForeignKeyConstraint,
    Index,
    MetaData,
    PrimaryKeyConstraint,
    Text,
    UniqueConstraint,
    event,
    inspect,
    text,
)
from sqlalchemy.orm import registry
from sqlmodel import Field, SQLModel

from .projects import validate_slug

AGENTS: tuple[str, ...] = ("claude", "cursor", "vscode", "codex")
"""Agents ``project_agents.agent`` accepts (the four ``whygraph.agents`` keys)."""

PROJECT_SOURCES: tuple[str, ...] = ("local", "github")
SECRET_KINDS: tuple[str, ...] = ("llm_api_key", "github_token", "claude_oauth_token")
SCAN_KINDS: tuple[str, ...] = ("scan", "sync")
SCAN_TRIGGERS: tuple[str, ...] = (
    "initial",
    "manual",
    "describe",
    "hook",
    "poll",
    "sync",
)
SCAN_STATUSES: tuple[str, ...] = (
    "queued",
    "running",
    "ok",
    "failed",
    "interrupted",
    "cancelled",
)


def _in(column: str, values: tuple[str, ...]) -> str:
    quoted = ", ".join(f"'{v}'" for v in values)
    return f"{column} IN ({quoted})"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _uid() -> str:
    return str(uuid.uuid4())


class PortalBase(SQLModel, registry=registry(metadata=MetaData())):
    """Declarative base of the portal tables; owns the portal ``MetaData``.

    Notes
    -----
    Use ``PortalBase.metadata`` (never ``SQLModel.metadata``) as the
    Alembic ``target_metadata`` for the portal chain.
    """


class Setting(PortalBase, table=True):
    """The single ``settings`` row (``CHECK (id = 1)``).

    Attributes
    ----------
    id : int
        Always ``1``.
    mode : str
        ``"local"`` or ``"production"`` (M2). Chosen at first start,
        never switchable from the web.
    created_at : str
        ISO-8601 UTC timestamp.
    schema_version : str or None
        Free-form portal schema label.
    """

    __tablename__ = "settings"
    __table_args__ = (
        CheckConstraint("id = 1", name="ck_settings_singleton"),
        CheckConstraint(_in("mode", ("local", "production")), name="ck_settings_mode"),
    )

    id: int = Field(default=1, primary_key=True)
    mode: str = Field(default="local", sa_type=Text)
    created_at: str = Field(default_factory=_now, sa_type=Text)
    schema_version: str | None = Field(default=None, sa_type=Text)


class User(PortalBase, table=True):
    """A portal user. Local mode has one, created by first-run setup.

    Attributes
    ----------
    uid : str
        Stable UUID4 - what M2 ownership columns reference, so a row
        survives a re-import that changes ``id``.
    display_name : str
        Shown in the UI.
    username, password_hash : str or None
        Unused in local mode (M2).
    role : str
        ``"owner"`` in M1.
    """

    __tablename__ = "users"
    __table_args__ = (UniqueConstraint("uid", name="uq_users_uid"),)

    id: int | None = Field(default=None, primary_key=True)
    uid: str = Field(default_factory=_uid, sa_type=Text)
    display_name: str = Field(sa_type=Text)
    username: str | None = Field(default=None, sa_type=Text)
    password_hash: str | None = Field(default=None, sa_type=Text)
    role: str = Field(default="owner", sa_type=Text)
    created_at: str = Field(default_factory=_now, sa_type=Text)


class Project(PortalBase, table=True):
    """A registered project.

    Attributes
    ----------
    slug : str
        Immutable identity (see :mod:`whygraph.portal.projects`).
    name : str
        Display name; the only renamable field.
    source : str
        ``"local"`` (a shared-folder repo mounted in place) or
        ``"github"`` (cloned by the portal under the data dir).
    root : str
        Absolute path for a local repo; relative to the data dir
        (``repos/<slug>``) for a GitHub clone.
    remote_url : str or None
        Git remote URL, when known.
    initialized_at, last_scan_at, last_scanned_head : str or None
        Lifecycle timestamps and the HEAD of the last successful scan.
    created_by : int or None
        ``users.id`` (M2 audit); ``NULL`` when the user is gone.
    """

    __tablename__ = "projects"
    __table_args__ = (
        UniqueConstraint("slug", name="uq_projects_slug"),
        UniqueConstraint("root", name="uq_projects_root"),
        CheckConstraint(_in("source", PROJECT_SOURCES), name="ck_projects_source"),
        ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_projects_created_by",
            ondelete="SET NULL",
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    slug: str = Field(sa_type=Text)
    name: str = Field(sa_type=Text)
    source: str = Field(sa_type=Text)
    root: str = Field(sa_type=Text)
    remote_url: str | None = Field(default=None, sa_type=Text)
    initialized_at: str | None = Field(default=None, sa_type=Text)
    last_scan_at: str | None = Field(default=None, sa_type=Text)
    last_scanned_head: str | None = Field(default=None, sa_type=Text)
    created_by: int | None = Field(default=None)
    created_at: str = Field(default_factory=_now, sa_type=Text)


class ProjectAgent(PortalBase, table=True):
    """One agent whose MCP config ``initialize`` wrote for a project."""

    __tablename__ = "project_agents"
    __table_args__ = (
        PrimaryKeyConstraint("project_id", "agent", name="pk_project_agents"),
        CheckConstraint(_in("agent", AGENTS), name="ck_project_agents_agent"),
        ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_project_agents_project",
            ondelete="CASCADE",
        ),
    )

    project_id: int = Field()
    agent: str = Field(sa_type=Text)
    configured_at: str = Field(default_factory=_now, sa_type=Text)


class ProjectConfig(PortalBase, table=True):
    """A config v2 layer: the global defaults (``project_id`` NULL) or one project's.

    ``config`` never holds a secret (:mod:`whygraph.portal.config_layers`
    rejects ``api_key`` / ``token``). Uniqueness is by partial indexes -
    a plain ``UNIQUE (project_id)`` would let repeated global saves
    duplicate the row, because SQLite treats ``NULL`` values as distinct.
    """

    __tablename__ = "project_config"
    __table_args__ = (
        ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_project_config_project",
            ondelete="CASCADE",
        ),
        Index(
            "uq_project_config_project",
            "project_id",
            unique=True,
            sqlite_where=text("project_id IS NOT NULL"),
        ),
        Index(
            "uq_project_config_global",
            text("(1)"),
            unique=True,
            sqlite_where=text("project_id IS NULL"),
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    project_id: int | None = Field(default=None)
    config: dict[str, Any] = Field(
        default_factory=dict, sa_column=Column(JSON, nullable=False)
    )
    updated_at: str = Field(default_factory=_now, sa_type=Text)


class Secret(PortalBase, table=True):
    """An encrypted secret, global (``project_id`` NULL) or per project.

    Attributes
    ----------
    kind : str
        ``"llm_api_key"`` (``provider`` set) or ``"github_token"``
        (``provider`` NULL).
    ciphertext : str
        Fernet token (:mod:`whygraph.portal.secrets`).
    hint : str
        ``"...a1b2"``-style last four characters, for display only.
    created_at : str
        When the current value was written (a re-save replaces the value
        in place and refreshes this).

    Notes
    -----
    Uniqueness is one partial index per scope over ``(kind,
    coalesce(provider, ''))``: ``provider`` is NULL for a GitHub token,
    and NULLs are distinct in a SQLite ``UNIQUE``.
    """

    __tablename__ = "secrets"
    __table_args__ = (
        CheckConstraint(_in("kind", SECRET_KINDS), name="ck_secrets_kind"),
        CheckConstraint(
            "(kind = 'llm_api_key') = (provider IS NOT NULL)",
            name="ck_secrets_provider",
        ),
        ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_secrets_project",
            ondelete="CASCADE",
        ),
        Index(
            "uq_secrets_project",
            "project_id",
            "kind",
            text("coalesce(provider, '')"),
            unique=True,
            sqlite_where=text("project_id IS NOT NULL"),
        ),
        Index(
            "uq_secrets_global",
            "kind",
            text("coalesce(provider, '')"),
            unique=True,
            sqlite_where=text("project_id IS NULL"),
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    project_id: int | None = Field(default=None)
    kind: str = Field(sa_type=Text)
    provider: str | None = Field(default=None, sa_type=Text)
    ciphertext: str = Field(sa_type=Text)
    hint: str = Field(sa_type=Text)
    created_at: str = Field(default_factory=_now, sa_type=Text)


class ScanRun(PortalBase, table=True):
    """One scan (or GitHub sync) run of a project (written by the runner, step 8).

    Attributes
    ----------
    kind : str
        ``"scan"`` or ``"sync"``.
    trigger : str
        ``"initial"``, ``"manual"``, ``"describe"``, ``"hook"``,
        ``"poll"`` or ``"sync"``.
    analyze : bool
        Whether the run describes commits (resolved from the trigger).
    requested_by : int or None
        ``users.id``; ``NULL`` for hook / poll / catch-up runs.
    status : str
        ``queued``, ``running``, ``ok``, ``failed``, ``interrupted`` or
        ``cancelled``.
    events_path, log_path : str or None
        Relative to the data dir (``runs/42.jsonl``).
    summary : str or None
        JSON-encoded result summary. While a ``sync`` row is queued it holds
        ``{"scan_requested": true}`` when a scan was merged into it, so a
        restart does not drop that scan.
    """

    __tablename__ = "scan_runs"
    __table_args__ = (
        CheckConstraint(_in("kind", SCAN_KINDS), name="ck_scan_runs_kind"),
        CheckConstraint(_in("trigger", SCAN_TRIGGERS), name="ck_scan_runs_trigger"),
        CheckConstraint(_in("status", SCAN_STATUSES), name="ck_scan_runs_status"),
        ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_scan_runs_project",
            ondelete="CASCADE",
        ),
        ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name="fk_scan_runs_requested_by",
            ondelete="SET NULL",
        ),
        Index("ix_scan_runs_project_id", "project_id"),
    )

    id: int | None = Field(default=None, primary_key=True)
    project_id: int = Field()
    kind: str = Field(default="scan", sa_type=Text)
    trigger: str = Field(sa_type=Text)
    analyze: bool = Field(default=True, sa_column=Column(Boolean, nullable=False))
    requested_by: int | None = Field(default=None)
    status: str = Field(default="queued", sa_type=Text)
    started_at: str | None = Field(default=None, sa_type=Text)
    finished_at: str | None = Field(default=None, sa_type=Text)
    events_path: str | None = Field(default=None, sa_type=Text)
    log_path: str | None = Field(default=None, sa_type=Text)
    summary: str | None = Field(default=None, sa_type=Text)


@event.listens_for(Project, "before_insert")
def _validate_slug_on_insert(mapper, connection, target: Project) -> None:  # noqa: ANN001
    """Reject a slug that breaks :data:`whygraph.portal.projects.SLUG_RE`."""
    validate_slug(target.slug)


@event.listens_for(Project, "before_update")
def _slug_is_immutable(mapper, connection, target: Project) -> None:  # noqa: ANN001
    """Refuse to change a flushed project's slug (only ``name`` is renamable)."""
    if inspect(target).attrs.slug.history.has_changes():
        raise ValueError("a project's slug is immutable; rename only its name")


__all__ = [
    "AGENTS",
    "PortalBase",
    "Project",
    "ProjectAgent",
    "ProjectConfig",
    "ScanRun",
    "Secret",
    "Setting",
    "User",
]
