#!/usr/bin/env sh
# WhyGraph installer — pure-Docker, no host Python/Node/gh needed.
#
# Drops a tiny `whygraph` (and `whygraph-mcp`) shim on your PATH that runs
# the WhyGraph container against the current directory, then pulls the
# image. After this, the whole workflow is just:
#
#   whygraph init      # in a repo: bootstrap DB + CodeGraph index
#   whygraph scan      # crawl history + refresh index + LLM descriptions
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/mtrdesign/whygraph/main/scripts/install.sh | sh
#
# Overrides (env vars):
#   WHYGRAPH_IMAGE     image to run        (default: ghcr.io/mtrdesign/whygraph:latest)
#   WHYGRAPH_BIN_DIR   where to install    (default: $HOME/.local/bin)

set -eu

IMAGE="${WHYGRAPH_IMAGE:-ghcr.io/mtrdesign/whygraph:latest}"
BIN_DIR="${WHYGRAPH_BIN_DIR:-$HOME/.local/bin}"

if ! command -v docker >/dev/null 2>&1; then
    echo "error: Docker is required but not found on PATH." >&2
    echo "       Install Docker first: https://docs.docker.com/get-docker/" >&2
    exit 1
fi

mkdir -p "$BIN_DIR"

# Write a shim for one console script ($1 = whygraph | whygraph-mcp).
# The shim resolves the image, host uid/gid, and a TTY at *run* time, so
# the values below that reference $IMAGE are interpolated now while the
# \$(...) / \$VAR forms are deliberately escaped to evaluate at run time.
write_shim() {
    name="$1"
    target="$BIN_DIR/$name"
    cat > "$target" <<EOF
#!/usr/bin/env sh
# WhyGraph shim — runs '$name' inside the WhyGraph container against the
# current directory. Generated by scripts/install.sh; safe to re-generate.
set -eu
IMAGE="\${WHYGRAPH_IMAGE:-$IMAGE}"

# Allocate a TTY only when attached to one, so progress bars render
# interactively but pipes / CI / MCP-over-stdio still work.
tty=""
[ -t 0 ] && [ -t 1 ] && tty="-t"

# --user + HOME=/tmp so files written into the repo (.whygraph/, .codegraph/)
# are owned by the host user and git sees matching ownership (no "dubious
# ownership"). Tokens / LLM keys pass through from the host env when set.
exec docker run --rm -i \$tty \\
    --user "\$(id -u):\$(id -g)" -e HOME=/tmp \\
    -v "\$PWD:/workspace" -w /workspace \\
    -e GH_TOKEN -e GITHUB_TOKEN \\
    -e ANTHROPIC_API_KEY -e OPENAI_API_KEY -e DEEPSEEK_API_KEY \\
    "\$IMAGE" $name "\$@"
EOF
    chmod +x "$target"
    echo "installed $target"
}

write_shim whygraph
write_shim whygraph-mcp

echo "pulling $IMAGE ..."
if ! docker pull "$IMAGE"; then
    echo "warning: could not pull $IMAGE." >&2
    echo "         Build it locally and set WHYGRAPH_IMAGE, e.g.:" >&2
    echo "           docker build -f docker/whygraph/Dockerfile -t whygraph:latest ." >&2
    echo "           WHYGRAPH_IMAGE=whygraph:latest whygraph version" >&2
fi

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "note: add $BIN_DIR to your PATH, e.g. 'export PATH=\"$BIN_DIR:\$PATH\"'" ;;
esac

echo "done. Try:  cd <your-repo> && whygraph init && whygraph scan"
